### ISSUE TITLE
Panic on export --for-zero-height

### ISSUE THREAD

**Issue by dongsam** [cosmos/gaia#1014]
## Summary of Bug

Panic occurs when `gaia export --for-zero-height` 

https://github.com/cosmos/gaia/blob/56db57cea8c5c33be4cefdc388829d5f59d0f65e/app/export.go#L160

because of current [`prepForZeroHeightGenesis`](https://github.com/cosmos/gaia/blob/56db57cea8c5c33be4cefdc388829d5f59d0f65e/app/export.go#L160) function using `addr := sdk.ValAddress(iter.Key()[1:])` to casting [variable-length addresses](https://github.com/cosmos/cosmos-sdk/issues/8345),
It should be `addr := sdk.ValAddress(stakingtypes.AddressFromValidatorsKey(iter.Key()))`

## Version

current main branch, `ea93ef13fd4f2325c2429048205b4edf032b9b49`,
[v6.0.0-rc1](https://github.com/cosmos/gaia/releases/tag/v6.0.0-rc1),
...

## Steps to Reproduce

1. Start gaia application 

```bash
export BINARY=gaiad
export HOME_APP=$HOME/.gaia
export CHAIN_ID=localnet
export VALIDATOR_1="struggle panic room apology luggage game screen wing want lazy famous eight robot picture wrap act uphold grab away proud music danger naive opinion"
export USER_1="guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host"
export USER_2="fuel obscure melt april direct second usual hair leave hobby beef bacon solid drum used law mercy worry fat super must ritual bring faculty"
export VALIDATOR_1_GENESIS_COINS=100000000000000000stake,10000000000uatom,10000000000uusd
export USER_1_GENESIS_COINS=10000000000stake,10000000000uatom,10000000000uusd
export USER_2_GENESIS_COINS=10000000000stake,10000000000poolD35A0CC16EE598F90B044CE296A405BA9C381E38837599D96F2F70C2F02A23A4,10000000000pool93E069B333B5ECEBFE24C6E1437E814003248E0DD7FF8B9F82119F4587449BA5,10000000000pool3036F43CB8131A1A63D2B3D3B11E9CF6FA2A2B6FEC17D5AD283C25C939614A8C,10000000000poolE4D2617BFE03E1146F6BBA1D9893F2B3D77BA29E7ED532BB721A39FF1ECC1B07

# Bootstrap
$BINARY init $CHAIN_ID --chain-id $CHAIN_ID
echo $VALIDATOR_1 | $BINARY keys add val1 --keyring-backend test --recover
echo $USER_1 | $BINARY keys add user1 --keyring-backend test --recover
echo $USER_2 | $BINARY keys add user2 --keyring-backend test --recover
$BINARY add-genesis-account $($BINARY keys show val1 --keyring-backend test -a) $VALIDATOR_1_GENESIS_COINS
$BINARY add-genesis-account $($BINARY keys show user1 --keyring-backend test -a) $USER_1_GENESIS_COINS
$BINARY add-genesis-account $($BINARY keys show user2 --keyring-backend test -a) $USER_2_GENESIS_COINS
$BINARY gentx val1 50000000000000000stake --chain-id $CHAIN_ID --keyring-backend test
$BINARY collect-gentxs

$BINARY start

```

2. Stop gaia after few blocks created and command `gaia export --for-zero-height` 

```bash

# stop gaia after few blocks created
$BINARY export --for-zero-height

2:50PM INF asserting crisis invariants inv=0/12 module=x/crisis name=bank/nonnegative-outstanding
2:50PM INF asserting crisis invariants inv=1/12 module=x/crisis name=bank/total-supply
2:50PM INF asserting crisis invariants inv=2/12 module=x/crisis name=staking/module-accounts
2:50PM INF asserting crisis invariants inv=3/12 module=x/crisis name=staking/nonnegative-power
2:50PM INF asserting crisis invariants inv=4/12 module=x/crisis name=staking/positive-delegation
2:50PM INF asserting crisis invariants inv=5/12 module=x/crisis name=staking/delegator-shares
2:50PM INF asserting crisis invariants inv=6/12 module=x/crisis name=gov/module-account
2:50PM INF asserting crisis invariants inv=7/12 module=x/crisis name=liquidity/escrow-amount
2:50PM INF asserting crisis invariants inv=8/12 module=x/crisis name=distribution/nonnegative-outstanding
2:50PM INF asserting crisis invariants inv=9/12 module=x/crisis name=distribution/can-withdraw
2:50PM INF asserting crisis invariants inv=10/12 module=x/crisis name=distribution/reference-count
2:50PM INF asserting crisis invariants inv=11/12 module=x/crisis name=distribution/module-account
2:50PM INF asserted all invariants duration=1.9918 height=5 module=x/crisis
panic: expected validator, not found

goroutine 1 [running]:
github.com/cosmos/gaia/v6/app.(*GaiaApp).prepForZeroHeightGenesis(0xc000e15800, 0x5f33328, 0xc0000440d8, 0x5f4c800, 0xc00011cd00, 0x0, 0x0, 0x0, 0x0, 0x5, ...)
	github.com/cosmos/gaia/v6/app/export.go:163 +0x1665
github.com/cosmos/gaia/v6/app.(*GaiaApp).ExportAppStateAndValidators(0xc000e15800, 0xc00130ba01, 0x6c81080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cosmos/gaia/v6/app/export.go:29 +0x588
github.com/cosmos/gaia/v6/cmd/gaiad/cmd.appCreator.appExport(0x5f3d4b8, 0xc000139470, 0x5f4f958, 0xc001153a40, 0x5f45c98, 0xc000efd700, 0xc000011168, 0x5f34010, 0xc00130ba40, 0x5f4bab8, ...)
	github.com/cosmos/gaia/v6/cmd/gaiad/cmd/root.go:254 +0x309
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0xc0011d2780, 0xc001270350, 0x0, 0x1, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.44.0/server/export.go:71 +0x45e
github.com/spf13/cobra.(*Command).execute(0xc0011d2780, 0xc001270340, 0x1, 0x1, 0xc0011d2780, 0xc001270340)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc001078f00, 0x0, 0x0, 0xc000f46eb8)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc001078f00, 0xc000f46eb8, 0x18, 0x5f4f958, 0xc001153a40)
	github.com/cosmos/cosmos-sdk@v0.44.0/server/cmd/execute.go:36 +0x285
main.main()
	github.com/cosmos/gaia/v6/cmd/gaiad/main.go:16 +0x45
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
thank you @dongsam !!

**Comment by yaruwangway** [comment]
Hi @dongsam, It seems v5.0.7 does not have the export error, only v6.0.0-rc1

**Comment by dongsam** [comment]
> Hi @dongsam, It seems v5.0.7 does not have the export error, only v6.0.0-rc1

Oh, You're right. It was my mistake. Thank you.
