### ISSUE TITLE
Panic on node start using exported state file

### ISSUE THREAD

**Issue by sosedoff** [cosmos/gaia#1047]
## Summary of Bug

Im not entirely sure if im doing this right, but i'm trying to generate an export file for a known height (from the archive node) and using it to start the node instead of starting at the genesis. The purpose is to get the node working from a specific height without relying on snapshots or state sync. "Lost" data prior to the start height is not important. 

## Version

Gaia v4.2.1

## Steps to Reproduce

Configure node with cosmoshub4 genesis (height 5200791), reset the state:

```bash
gaiad unsafe-reset-all
gaiad start --x-crisis-skip-assert-invariants
```

Let it run for a bit to sync a bunch of blocks. Stop the node. 

Generate export file (i used 5202355):

```bash
# Export the state for a last known height
gaiad export --height 5202355 > 5202355.json

# Inspect the initial height
cat 5202355.json | jq -r | grep initial_height
# => "initial_height": "5202356",
```

Replace genesis with exported file, reset data and start the node:

```bash
cat 5202355.json > ~/.gaia/config/genesis.json
gaiad unsafe-reset-all
gaiad start --x-crisis-skip-assert-invariants
```

Gaia node panics:

```
11:51AM INF starting ABCI with Tendermint
11:51AM INF Starting multiAppConn service impl=multiAppConn module=proxy
11:51AM INF Starting localClient service connection=query impl=localClient module=abci-client
11:51AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
11:51AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
11:51AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
11:51AM INF Starting EventBus service impl=EventBus module=events
11:51AM INF Starting PubSub service impl=PubSub module=pubsub
11:51AM INF Starting IndexerService service impl=IndexerService module=txindex
11:51AM INF Starting ExtractorService service impl=ExtractorService module=extractor
11:51AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
11:51AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
11:52AM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus
11:52AM INF Version info block=11 p2p=8 software=v0.34.9-figment-4
11:52AM INF This node is not a validator addr=F5EEBAD93D0F107AF540DE745DC4B6B830F02391 module=consensus pubKey=EeETldXRYoiVgEzIH7oBXFyy2s8my1pGVdjdRGH4WXE=
11:52AM INF P2P Node ID ID=0e647084c5abe8cb6b1bf846739524e680de669d file=/Users/sosedoff/.gaia/config/node_key.json module=p2p
11:52AM INF Add our address to book addr={"id":"0e647084c5abe8cb6b1bf846739524e680de669d","ip":"0.0.0.0","port":26656} book=/Users/sosedoff/.gaia/config/addrbook.json module=p2p
11:52AM INF Starting Node service impl=Node
11:52AM INF Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server
11:52AM INF Starting P2P Switch service impl="P2P Switch" module=p2p
11:52AM INF Starting Mempool service impl=Mempool module=mempool
11:52AM INF Starting BlockchainReactor service impl=BlockchainReactor module=blockchain
11:52AM INF Starting BlockPool service impl=BlockPool module=blockchain
11:52AM INF Starting Consensus service impl=ConsensusReactor module=consensus
11:52AM INF Reactor  module=consensus waitSync=true
11:52AM INF Starting Evidence service impl=Evidence module=evidence
11:52AM INF Starting StateSync service impl=StateSync module=statesync
11:52AM INF Starting PEX service impl=PEX module=pex
11:52AM INF Starting AddrBook service book=/Users/sosedoff/.gaia/config/addrbook.json impl=AddrBook module=p2p
11:52AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=64
11:52AM INF No addresses to dial. Falling back to seeds module=pex
11:52AM INF Saving AddrBook to file book=/Users/sosedoff/.gaia/config/addrbook.json module=p2p size=24
11:52AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
11:52AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}

panic: Failed to process committed block (5202356:8BCAA500ADFD01C368ACC2543A459B939F9F73EC52E343004FA33C4A4DC11627): wrong Block.Header.LastBlockID.  Expected :0:000000000000, got B046C990E3F5871D1B1326D2E9357E2F7288EA952DBFEA4252F38BCC10394CA0:1:38D744D48F48
goroutine 184310 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0x140001e81c0, 0x0)
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:401 +0x10e4
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.9/blockchain/v0/reactor.go:110 +0x6c

```

Or is the `export` output is only meant for upgrades?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by sosedoff** [comment]
Any thoughts on this at all?

**Comment by yaruwangway** [comment]
I am not sure a genesis exported at any height which is not upgrade height, can be used as the genesis for direct sync. 

@faddat  can you help with this ? Is that correct ? Thank you!

**Comment by sosedoff** [comment]
@yaruwangway appreciate the triage. Wasn't sure if exported genesis was only meant for upgrades, but if there's a workaround (even by patching tendermint/sdk etc) i can def use a pointer.

**Comment by nooomski** [comment]
Anyone else got some ideas here @faddat @yaruwangway @okwme ?

**Comment by faddat** [comment]
Hey guys I missed the first ping on this one. We are having similar problems with Osmosis and I think that our team member Khanh may have some insights.  

 certainly I would like to see better snapshots

**Comment by sosedoff** [comment]
Glad someone else is having a look into this

**Comment by nooomski** [comment]
@faddat thanks! What's Khanh's github handle? Do you think he has time to share his insights here?

**Comment by uhvyuhs77** [comment]
Thank you I'm Uhvyuhs77 I am honored

**Comment by ValarDragon** [comment]
This should definitely not work, and probably never will work. (Or at minimum, won't work until SMT migration)

At a glance, theres two problems:
* A lot of state changes happen in preparing a genesis file (e.g. one historic example was you auto-withdrew staking rewards)
* IAVL is insertion order dependent. So when you go to genesis file, you just lose that data entirely. (as the tree structure is not merkelized)

**Comment by uhvyuhs77** [comment]
gaiad unsafe-reset-all
gaiad start --x-crisis-skip-assert-invariants

**Comment by sosedoff** [comment]
Based on all details that i've come across, it seems not possible to utilize the state export file for anything other than upgrades.
