### ISSUE TITLE
Upgrade to v6.0.0 error

### ISSUE THREAD

**Issue by vae520283995** [cosmos/gaia#1082]
My current version is v5.0.8, I git clone -b v6.0.0 and then make install, restart the node

```
3:27AM INF starting ABCI with Tendermint
3:27AM INF Starting multiAppConn service impl=multiAppConn module=proxy
3:27AM INF Starting localClient service connection=query impl=localClient module=abci-client
3:27AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
3:27AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
3:27AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
3:27AM INF Starting EventBus service impl=EventBus module=events
3:27AM INF Starting PubSub service impl=PubSub module=pubsub
3:27AM INF Starting IndexerService service impl=IndexerService module=txindex
3:27AM INF ABCI Handshake App Info hash="�\"Iuk$8F�όT�)�[d�Ɂ({Ҭ\x19)LG��h/" height=8484636 module=consensus protocol-version=0 software-version=v6.0.0
3:27AM INF ABCI Replay Blocks appHeight=8484636 module=consensus stateHeight=8484636 storeHeight=8484637
3:27AM INF Replay last block using real app module=consensus
3:27AM ERR WARNING: Attempt to allocate proposer rewards to unknown proposer cosmosvalcons1qq92t2l4jz5pt67tmts8ptl4p0jhr6utx5xa8y. This should happen only if the proposer unbonded completely within a single block, which generally should not happen except in exceptional circumstances (or fuzz testing). We recommend you investigate immediately. module=x/distribution
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x16f047a]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.AllocateTokensToValidator(0x23a8e30, 0xc005bba2d0, 0x23dd0b8, 0xc00108d7f0, 0x23dd0b8, 0xc00108d7f0, 0xc00056ee38, 0x23a8e30, 0xc005bba300, 0x23a8e80, ...)
	github.com/cosmos/cosmos-sdk@v0.44.3/x/distribution/keeper/allocation.go:107 +0x3a
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.AllocateTokens(0x23a8e30, 0xc005bba2d0, 0x23dd0b8, 0xc00108d7f0, 0x23dd0b8, 0xc00108d7f0, 0xc00056ee38, 0x23a8e30, 0xc005bba300, 0x23a8e80, ...)
	github.com/cosmos/cosmos-sdk@v0.44.3/x/distribution/keeper/allocation.go:95 +0x12f0
github.com/cosmos/cosmos-sdk/x/distribution.BeginBlocker(0x23c6448, 0xc0000440e0, 0x23dfe60, 0xc00356c680, 0xb, 0x0, 0xc01f9285d0, 0xb, 0x81771d, 0x204434a7, ...)
	github.com/cosmos/cosmos-sdk@v0.44.3/x/distribution/abci.go:32 +0x488
github.com/cosmos/cosmos-sdk/x/distribution.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.44.3/x/distribution/module.go:170
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000c14230, 0x23c6448, 0xc0000440e0, 0x23dfe60, 0xc00356c680, 0xb, 0x0, 0xc01f9285d0, 0xb, 0x81771d, ...)
	github.com/cosmos/cosmos-sdk@v0.44.3/types/module/module.go:450 +0x1d8
github.com/cosmos/gaia/v6/app.(*GaiaApp).BeginBlocker(...)
	github.com/cosmos/gaia/v6/app/app.go:628
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc00019a000, 0xc01fa54fe0, 0x20, 0x20, 0xb, 0x0, 0xc01f9285d0, 0xb, 0x81771d, 0x204434a7, ...)
	github.com/cosmos/cosmos-sdk@v0.44.3/baseapp/abci.go:193 +0x7b8
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000dafec0, 0xc01fa54fe0, 0x20, 0x20, 0xb, 0x0, 0xc01f9285d0, 0xb, 0x81771d, 0x204434a7, ...)
	github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0xfa
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc004004770, 0xc01fa54fe0, 0x20, 0x20, 0xb, 0x0, 0xc01f9285d0, 0xb, 0x81771d, 0x204434a7, ...)
	github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x75
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x23c71a0, 0xc000bd0300, 0x23d3c58, 0xc004004770, 0xc000e46b40, 0x23dcbe8, 0xc0040054c0, 0x4f5b97, 0xc004f76600, 0x20, ...)
	github.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x51b
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0043d8c40, 0xb, 0x0, 0xc008332030, 0x7, 0xc008332040, 0xb, 0x4f5b97, 0x81771c, 0xc004f76600, ...)
	github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x168
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc01fa71c18, 0xb, 0x0, 0xc008332030, 0x7, 0xc008332040, 0xb, 0x4f5b97, 0x81771c, 0xc004f76600, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:503 +0x292
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0066d1c18, 0xb, 0x0, 0xc008332030, 0x7, 0xc008332040, 0xb, 0x4f5b97, 0x81771c, 0xc004f76600, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:416 +0xd79
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01fa71c18, 0x23e10c8, 0xc0005692b0, 0x1f4, 0xc000f05b70)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x23dcbe8, 0xc0040054c0, 0xb, 0x0, 0xc008332030, 0x7, 0xc008332040, 0xb, 0x4f5b97, 0x81771c, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0005428c0, 0x23bd630, 0xc000c16640, 0xc005bba080, 0x2385e80, 0xc008320438, 0xc005bba140, 0x2174278, 0xc005bba530, 0x23c71a0, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x2105
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000c09fa0, 0x0, 0x0, 0x0, 0x23ea8b8, 0xc0001a7260, 0x0, 0x0, 0x23d0710, 0xc00108d7f0, ...)
	github.com/cosmos/cosmos-sdk@v0.44.3/server/start.go:263 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000bdf900, 0xc000e9ac30, 0x0, 0x5, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.44.3/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc000bdf900, 0xc000e9abe0, 0x5, 0x5, 0xc000bdf900, 0xc000e9abe0)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c18280, 0x0, 0x0, 0xc00106fd00)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000c18280, 0xc00106fd00, 0xb, 0x23e3058, 0xc00108d7f0)
	github.com/cosmos/cosmos-sdk@v0.44.3/server/cmd/execute.go:36 +0x285
main.main()
	github.com/cosmos/gaia/v6/cmd/gaiad/main.go:16 +0x45
```

**Comment by vae520283995** [comment]
@yaruwangway Can you help?

**Comment by yaruwangway** [comment]
Hi @vae520283995 , can you give more info. ?
you are running a local test ? syncing the live cosmoshub ? or joining the [vega public testnet](https://github.com/cosmos/vega-test/blob/master/public-testnet/README.md) ?

The cosmohub is not running on v6.0.0 yet. The upgrade is in schedule.
If you are syncing the the live cosmoshub now, you just need to wait till the upgrade height, your node will panic. and at this moment, you can switch the binary from v5 to v6.
If you do not take care of the panic and want to automatically upgrade your node, you can use cosmovisor. Here are some examples for how to use cosmovisor:
https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor
https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor
https://github.com/cosmos/vega-test/tree/master/local-testnet#cosmovisor

**Comment by vae520283995** [comment]
> Hi @vae520283995 , can you give more info. ? you are running a local test ? syncing the live cosmoshub ? or joining the [vega public testnet](https://github.com/cosmos/vega-test/blob/master/public-testnet/README.md) ?
> 
> The cosmohub is not running on v6.0.0 yet. The upgrade is in schedule. If you are syncing the the live cosmoshub now, you just need to wait till the upgrade height, your node will panic. and at this moment, you can switch the binary from v5 to v6. If you do not take care of the panic and want to automatically upgrade your node, you can use cosmovisor. Here are some examples for how to use cosmovisor: https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor https://github.com/cosmos/vega-test/tree/master/local-testnet#cosmovisor

Thank you, I am running live cosmoshub, I have downgraded to v5.0.8, and I will upgrade to v6.0.0 when I reach the upgrade height
