### ISSUE TITLE
 panic: stored supply should not have been nil & panic: ERROR: Message: "no delegation distribution info"

### ISSUE THREAD

**Issue by dev-lc** [cosmos/gaia#128]
## Summary of Bug

Trying to run a Full-Node according to the [Doc](https://hub.cosmos.network/docs/join-mainnet.html) I've been facing with two errors (pls look at the _Steps to Reproduce_ section). I fix one of the errors (I hope it's acceptable), but another appears.
Please help with resolution and update your Docs to avoid them by other people.

## Version

name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.0
commit: 3c70fee433956ba32e35705193a5f7a7d5b63277
build_tags: netgo,ledger
go: go version go1.13 linux/amd64

All actions are proceeded in a brand new Docker environment, based on the latest official image "docker.io/golang". Thus we can consider that it's a clean installation

## Steps to Reproduce

```
root@cosmos-atom:# pwd
/root
root@cosmos-atom:# 
root@cosmos-atom:# ls -la
total 16
drwxr-xr-x. 4 root root    71 Sep 16 12:19 .
drwxr-xr-x. 1 root root    17 Sep 16 12:17 ..
-rw-------. 1 root root  3137 Sep 16 12:17 .bash_history
drwxr-xr-x. 2 root root    24 Sep 16 12:19 .vim
-rw-------. 1 root root 12064 Sep 16 12:19 .viminfo
drwxr-xr-x. 2 root root    63 Sep 16 10:15 gaia_bkp
root@cosmos-atom:# 
root@cosmos-atom:# go version 
go version go1.13 linux/amd64
root@cosmos-atom:# 
root@cosmos-atom:# git clone -b "v2.0.0" https://github.com/cosmos/gaia
Cloning into 'gaia'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1415 (delta 10), reused 12 (delta 8), pack-reused 1382
Receiving objects: 100% (1415/1415), 6.87 MiB | 6.87 MiB/s, done.
Resolving deltas: 100% (670/670), done.
Note: checking out '3c70fee433956ba32e35705193a5f7a7d5b63277'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

root@cosmos-atom:# 
root@cosmos-atom:# 
root@cosmos-atom:# cd gaia && make install
go: finding github.com/cosmos/cosmos-sdk v0.37.0
--> Ensure dependencies have not been modified
all modules verified
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=2.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=3c70fee433956ba32e35705193a5f7a7d5b63277 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiad
go: downloading github.com/tendermint/tendermint v0.32.2
go: downloading github.com/cosmos/cosmos-sdk v0.37.0
go: downloading github.com/tendermint/tm-db v0.1.1
go: extracting github.com/tendermint/tm-db v0.1.1
go: downloading github.com/pkg/errors v0.8.1
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/tendermint/tendermint v0.32.2
go: extracting github.com/cosmos/cosmos-sdk v0.37.0
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20190318030020-c3a204f8e965
go: downloading github.com/otiai10/copy v1.0.1
go: downloading github.com/tendermint/go-amino v0.15.0
go: extracting github.com/otiai10/copy v1.0.1
go: extracting github.com/tendermint/go-amino v0.15.0
go: extracting github.com/syndtr/goleveldb v1.0.1-0.20190318030020-c3a204f8e965
go: downloading golang.org/x/net v0.0.0-20190724013045-ca1201d0de80
go: downloading github.com/gorilla/mux v1.7.3
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/spf13/viper v1.4.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/pelletier/go-toml v1.4.0
go: downloading github.com/gogo/protobuf v1.2.1
go: extracting github.com/gorilla/mux v1.7.3
go: extracting github.com/davecgh/go-spew v1.1.1
go: extracting github.com/spf13/viper v1.4.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/go-kit/kit v0.9.0
go: extracting github.com/spf13/pflag v1.0.3
go: extracting gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/rakyll/statik v0.1.6
go: extracting github.com/golang/protobuf v1.3.2
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: extracting github.com/mitchellh/mapstructure v1.1.2
go: extracting github.com/pelletier/go-toml v1.4.0
go: downloading golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
go: extracting github.com/hashicorp/hcl v1.0.0
go: downloading github.com/bartekn/go-bip39 v0.0.0-20171116152956-a05967ea095d
go: downloading github.com/tendermint/crypto v0.0.0-20180820045704-3764759f34a5
go: extracting google.golang.org/grpc v1.22.0
go: extracting github.com/rakyll/statik v0.1.6
go: extracting golang.org/x/net v0.0.0-20190724013045-ca1201d0de80
go: downloading github.com/bgentry/speakeasy v0.1.0
go: extracting github.com/go-kit/kit v0.9.0
go: extracting github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading golang.org/x/sys v0.0.0-20190804053845-51ab0e2deafa
go: extracting github.com/bartekn/go-bip39 v0.0.0-20171116152956-a05967ea095d
go: downloading github.com/spf13/cobra v0.0.5
go: downloading github.com/libp2p/go-buffer-pool v0.0.1
go: extracting github.com/bgentry/speakeasy v0.1.0
go: extracting golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
go: extracting github.com/magiconair/properties v1.8.1
go: downloading github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c
go: extracting github.com/spf13/cobra v0.0.5
go: extracting github.com/gogo/protobuf v1.2.1
go: downloading github.com/cosmos/go-bip39 v0.0.0-20180819234021-555e2067c45d
go: extracting github.com/libp2p/go-buffer-pool v0.0.1
go: extracting github.com/tendermint/crypto v0.0.0-20180820045704-3764759f34a5
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/tendermint/btcd v0.1.1
go: downloading github.com/rs/cors v1.6.0
go: downloading github.com/spf13/cast v1.3.0
go: extracting github.com/cosmos/go-bip39 v0.0.0-20180819234021-555e2067c45d
go: extracting github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/rs/cors v1.6.0
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading github.com/cosmos/ledger-cosmos-go v0.10.3
go: extracting github.com/stretchr/testify v1.3.0
go: downloading github.com/prometheus/client_golang v1.0.0
go: extracting golang.org/x/sys v0.0.0-20190804053845-51ab0e2deafa
go: extracting github.com/cosmos/ledger-cosmos-go v0.10.3
go: downloading google.golang.org/genproto v0.0.0-20190701230453-710ae3a149df
go: extracting github.com/spf13/cast v1.3.0
go: downloading github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
go: extracting github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c
go: extracting github.com/gorilla/websocket v1.4.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/tendermint/iavl v0.12.4
go: extracting github.com/prometheus/client_golang v1.0.0
go: extracting github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
go: downloading github.com/spf13/afero v1.2.2
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/cosmos/ledger-go v0.9.2
go: extracting github.com/tendermint/btcd v0.1.1
go: downloading github.com/mattn/go-isatty v0.0.8
go: extracting github.com/golang/snappy v0.0.1
go: downloading github.com/prometheus/common v0.6.0
go: extracting github.com/mattn/go-isatty v0.0.8
go: extracting github.com/cosmos/ledger-go v0.9.2
go: downloading github.com/prometheus/procfs v0.0.3
go: downloading github.com/beorn7/perks v1.0.0
go: extracting github.com/prometheus/common v0.6.0
go: downloading github.com/zondax/hid v0.9.0
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/beorn7/perks v1.0.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: extracting github.com/prometheus/procfs v0.0.3
go: downloading github.com/go-logfmt/logfmt v0.4.0
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/spf13/afero v1.2.2
go: extracting github.com/tendermint/iavl v0.12.4
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/zondax/hid v0.9.0
go: extracting github.com/go-logfmt/logfmt v0.4.0
go: extracting github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: extracting github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting golang.org/x/text v0.3.2
go: extracting google.golang.org/genproto v0.0.0-20190701230453-710ae3a149df
go: finding github.com/spf13/cobra v0.0.5
go: finding github.com/gogo/protobuf v1.2.1
go: finding github.com/tendermint/go-amino v0.15.0
go: finding github.com/spf13/viper v1.4.0
go: finding github.com/tendermint/tendermint v0.32.2
go: finding github.com/bgentry/speakeasy v0.1.0
go: finding github.com/gorilla/mux v1.7.3
go: finding github.com/tendermint/tm-db v0.1.1
go: finding github.com/bartekn/go-bip39 v0.0.0-20171116152956-a05967ea095d
go: finding github.com/pelletier/go-toml v1.4.0
go: finding github.com/mattn/go-isatty v0.0.8
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/rakyll/statik v0.1.6
go: finding golang.org/x/sys v0.0.0-20190804053845-51ab0e2deafa
go: finding github.com/go-kit/kit v0.9.0
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/syndtr/goleveldb v1.0.1-0.20190318030020-c3a204f8e965
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c
go: finding github.com/go-logfmt/logfmt v0.4.0
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/otiai10/copy v1.0.1
go: finding github.com/cosmos/go-bip39 v0.0.0-20180819234021-555e2067c45d
go: finding golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/tendermint/iavl v0.12.4
go: finding github.com/golang/protobuf v1.3.2
go: finding github.com/cosmos/ledger-cosmos-go v0.10.3
go: finding github.com/spf13/afero v1.2.2
go: finding github.com/spf13/cast v1.3.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/tendermint/crypto v0.0.0-20180820045704-3764759f34a5
go: finding github.com/tendermint/btcd v0.1.1
go: finding github.com/spf13/jwalterweatherman v1.1.0
go: finding golang.org/x/net v0.0.0-20190724013045-ca1201d0de80
go: finding github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
go: finding google.golang.org/grpc v1.22.0
go: finding github.com/cosmos/ledger-go v0.9.2
go: finding golang.org/x/text v0.3.2
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/zondax/hid v0.9.0
go: finding github.com/prometheus/client_golang v1.0.0
go: finding github.com/rs/cors v1.6.0
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/beorn7/perks v1.0.0
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: finding github.com/prometheus/common v0.6.0
go: finding google.golang.org/genproto v0.0.0-20190701230453-710ae3a149df
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/prometheus/procfs v0.0.3
go: finding github.com/libp2p/go-buffer-pool v0.0.1
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.ServerName=gaiad -X github.com/cosmos/cosmos-sdk/version.ClientName=gaiacli -X github.com/cosmos/cosmos-sdk/version.Version=2.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=3c70fee433956ba32e35705193a5f7a7d5b63277 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' ./cmd/gaiacli
root@cosmos-atom:~/gaia# 
root@cosmos-atom:~/gaia# 
root@cosmos-atom:~/gaia# gaiad version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.0
commit: 3c70fee433956ba32e35705193a5f7a7d5b63277
build_tags: netgo,ledger
go: go version go1.13 linux/amd64

root@cosmos-atom:~/gaia# 
root@cosmos-atom:~/gaia# gaiad init test0357837135
{"app_message":{"accounts":[],"auth":{"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"bank":{"send_enabled":true},"crisis":{"constant_fee":{"amount":"1000","denom":"stake"}},"distribution":{"base_proposer_reward":"0.010000000000000000","bonus_proposer_reward":"0.040000000000000000","community_tax":"0.020000000000000000","delegator_starting_infos":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[],"withdraw_addr_enabled":true},"genutil":{"gentxs":null},"gov":{"deposit_params":{"max_deposit_period":"172800000000000","min_deposit":[{"amount":"10000000","denom":"stake"}]},"deposits":null,"proposals":null,"starting_proposal_id":"1","tally_params":{"quorum":"0.334000000000000000","threshold":"0.500000000000000000","veto":"0.334000000000000000"},"votes":null,"voting_params":{"voting_period":"172800000000000"}},"mint":{"minter":{"annual_provisions":"0.000000000000000000","inflation":"0.130000000000000000"},"params":{"blocks_per_year":"6311520","goal_bonded":"0.670000000000000000","inflation_max":"0.200000000000000000","inflation_min":"0.070000000000000000","inflation_rate_change":"0.130000000000000000","mint_denom":"stake"}},"params":null,"slashing":{"missed_blocks":{},"params":{"downtime_jail_duration":"600000000000","max_evidence_age":"120000000000","min_signed_per_window":"0.500000000000000000","signed_blocks_window":"100","slash_fraction_double_sign":"0.050000000000000000","slash_fraction_downtime":"0.010000000000000000"},"signing_infos":{}},"staking":{"delegations":null,"exported":false,"last_total_power":"0","last_validator_powers":null,"params":{"bond_denom":"stake","max_entries":7,"max_validators":100,"unbonding_time":"1814400000000000"},"redelegations":null,"unbonding_delegations":null,"validators":null},"supply":{"supply":[]}},"chain_id":"test-chain-38yXiy","gentxs_dir":"","moniker":"test0357837135","node_id":"67fa04ce6846c5bbf7de31c1ab70ff6fea05f179"}
root@cosmos-atom:~/gaia# 
root@cosmos-atom:~/gaia# 
root@cosmos-atom:~/gaia# cd ~
root@cosmos-atom:# pwd
/root
root@cosmos-atom:# 
root@cosmos-atom:# ls -la
total 20
drwxr-xr-x.  7 root root   111 Sep 16 12:23 .
drwxr-xr-x.  1 root root    27 Sep 16 12:17 ..
-rw-------.  1 root root  3137 Sep 16 12:17 .bash_history
drwxr-xr-x.  3 root root    22 Sep 16 12:20 .cache
drwx------.  4 root root    32 Sep 16 12:23 .gaiad
drwxr-xr-x.  2 root root    24 Sep 16 12:19 .vim
-rw-------.  1 root root 12064 Sep 16 12:19 .viminfo
drwxr-xr-x. 12 root root  4096 Sep 16 12:20 gaia
drwxr-xr-x.  2 root root    63 Sep 16 10:15 gaia_bkp
root@cosmos-atom:# 
root@cosmos-atom:# curl https://raw.githubusercontent.com/cosmos/launch/master/genesis.json > $HOME/.gaiad/config/genesis.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3310k  100 3310k    0     0  2283k      0  0:00:01  0:00:01 --:--:-- 2283k
root@cosmos-atom:# 
root@cosmos-atom:# 
root@cosmos-atom:# sed -i 's/seeds = ""/seeds = "6be0856f6365559fdc2e9e97a07d609f754632b0@cosmos-cosmoshub-2-seed.nodes.polychainlabs.com:26656"/g' .gaiad/config/config.toml 
root@cosmos-atom:# 
root@cosmos-atom:# cat ~/.gaiad/config/config.toml | fgrep 'seeds ='
seeds = "6be0856f6365559fdc2e9e97a07d609f754632b0@cosmos-cosmoshub-2-seed.nodes.polychainlabs.com:26656"
root@cosmos-atom:# 
root@cosmos-atom:# echo 'minimum-gas-prices = "0.025uatom"' | tee ~/.gaiad/config/config.toml
minimum-gas-prices = "0.025uatom"
root@cosmos-atom:# 
root@cosmos-atom:# 
root@cosmos-atom:# gaiad start
I[2019-09-16|14:06:16.066] Starting ABCI with Tendermint                module=main 
panic: stored supply should not have been nil

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/supply/internal/keeper.Keeper.GetSupply(0xc00010c540, 0x155b600, 0xc0009074b0, 0x156b500, 0xc00010ca10, 0x7f49103599b8, 0xc0000f8b60, 0xc000989ce0, 0x156a480, 0xc0000b4040, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/supply/internal/keeper/keeper.go:50 +0x18f
github.com/cosmos/cosmos-sdk/x/supply/internal/keeper.TotalSupply.func1(0x156a480, 0xc0000b4040, 0x157af00, 0xc000a3cc80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/supply/internal/keeper/invariants.go:27 +0xe7
github.com/cosmos/cosmos-sdk/x/crisis/internal/keeper.Keeper.AssertInvariants(0xc0008f4280, 0xb, 0x10, 0xc00010c540, 0x155b600, 0xc000907500, 0x155b640, 0xc000907520, 0xc0009d6120, 0x6, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/crisis/internal/keeper/keeper.go:74 +0x36d
github.com/cosmos/cosmos-sdk/x/crisis.AppModule.InitGenesis(0xc0000e5328, 0x156a480, 0xc0000b4040, 0x157af00, 0xc000a3cc80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/crisis/module.go:113 +0x2dd
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc00010ce00, 0x156a480, 0xc0000b4040, 0x157af00, 0xc000a3cc80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/types/module/module.go:258 +0x278
github.com/cosmos/gaia/app.(*GaiaApp).InitChainer(0xc0000e4f00, 0x156a480, 0xc0000b4040, 0x157af00, 0xc000a3cc80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/gaia/app/app.go:247 +0x11d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0000c2ea0, 0x0, 0xed44fea10, 0x0, 0xc000036250, 0xb, 0xc000a3cbc0, 0xc000ae1000, 0x63, 0x63, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/baseapp/baseapp.go:392 +0x2c7
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0005b3560, 0x0, 0xed44fea10, 0x0, 0xc000036250, 0xb, 0xc000a3cbc0, 0xc000ae1000, 0x63, 0x63, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/abci/client/local_client.go:223 +0x101
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0009370a0, 0x0, 0xed44fea10, 0x0, 0xc000036250, 0xb, 0xc000a3cbc0, 0xc000ae1000, 0x63, 0x63, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/proxy/app_conn.go:65 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0031610f0, 0xa, 0x0, 0x119bb6c, 0x6, 0xc000036250, 0xb, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/consensus/replay.go:309 +0x666
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0031610f0, 0x157d800, 0xc00010d1f0, 0x80, 0x1012300)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/consensus/replay.go:267 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x157cd80, 0xc000010210, 0xa, 0x0, 0x119bb6c, 0x6, 0xc000036250, 0xb, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:274 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc0000e2c80, 0x1565240, 0xc000033d60, 0xc000907870, 0x154c0a0, 0xc0009799a0, 0xc000907ae0, 0x13979c0, 0xc000907af0, 0x156afc0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:584 +0x334
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00053fb00, 0x13981c8, 0x1d, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/server/start.go:129 +0x4c1
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000479180, 0x1db18b0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/server/start.go:43 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000479180, 0x1db18b0, 0x0, 0x0, 0xc000479180, 0x1db18b0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bec80, 0x11c0836, 0xc000877ea0, 0x5977b2)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000bec80, 0x13985e8, 0x11a6115, 0x10)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/libs/cli/setup.go:89 +0x3c
main.main()
	/root/gaia/cmd/gaiad/main.go:68 +0x875
root@cosmos-atom:# 
root@cosmos-atom:#     
root@cosmos-atom:# gaiad unsafe-reset-all
I[2019-09-16|14:07:32.249] Removed all blockchain history               module=main dir=/root/.gaiad/data
I[2019-09-16|14:07:32.251] Reset private validator file to genesis state module=main keyFile=/root/.gaiad/config/priv_validator_key.json stateFile=/root/.gaiad/data/priv_validator_state.json
root@cosmos-atom:# 
root@cosmos-atom:# 
root@cosmos-atom:# gaiad start
I[2019-09-16|14:07:42.857] Starting ABCI with Tendermint                module=main 
panic: ERROR:
Codespace: distr
Code: 104
Message: "no delegation distribution info"


goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/distribution/keeper.CanWithdrawInvariant.func1.1(0x0, 0x1583d40, 0xc0002e8620, 0xc0002e8620)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/distribution/keeper/invariants.go:87 +0x6f9
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.IterateValidators(0x155b600, 0xc000240580, 0x155b640, 0xc0002405f0, 0xc000a30770, 0x1576fe0, 0xc000090540, 0x157b080, 0xc000230940, 0xc000a30770, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/staking/keeper/alias_functions.go:22 +0x206
github.com/cosmos/cosmos-sdk/x/distribution/keeper.CanWithdrawInvariant.func1(0x156a480, 0xc000036058, 0x157af00, 0xc00031f380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/distribution/keeper/invariants.go:80 +0x4ce
github.com/cosmos/cosmos-sdk/x/crisis/internal/keeper.Keeper.AssertInvariants(0xc0001da280, 0xb, 0x10, 0xc000a30770, 0x155b600, 0xc0002405e0, 0x155b640, 0xc000240600, 0xc0001cfa60, 0x6, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/crisis/internal/keeper/keeper.go:74 +0x36d
github.com/cosmos/cosmos-sdk/x/crisis.AppModule.InitGenesis(0xc0000d7328, 0x156a480, 0xc000036058, 0x157af00, 0xc00031f380, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/x/crisis/module.go:113 +0x2dd
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000a310a0, 0x156a480, 0xc000036058, 0x157af00, 0xc00031f380, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/types/module/module.go:258 +0x278
github.com/cosmos/gaia/app.(*GaiaApp).InitChainer(0xc0000d6f00, 0x156a480, 0xc000036058, 0x157af00, 0xc00031f380, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/gaia/app/app.go:247 +0x11d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00013d560, 0x0, 0xed44fea10, 0x0, 0xc000037bd0, 0xb, 0xc00031f2c0, 0xc000a6f000, 0x63, 0x63, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/baseapp/baseapp.go:392 +0x2c7
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0000afbc0, 0x0, 0xed44fea10, 0x0, 0xc000037bd0, 0xb, 0xc00031f2c0, 0xc000a6f000, 0x63, 0x63, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/abci/client/local_client.go:223 +0x101
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000012530, 0x0, 0xed44fea10, 0x0, 0xc000037bd0, 0xb, 0xc00031f2c0, 0xc000a6f000, 0x63, 0x63, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/proxy/app_conn.go:65 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0034130f0, 0xa, 0x0, 0x119bb6c, 0x6, 0xc000037bd0, 0xb, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/consensus/replay.go:309 +0x666
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0034130f0, 0x157d800, 0xc00013b0a0, 0x80, 0x1012300)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/consensus/replay.go:267 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x157cd80, 0xc000018390, 0xa, 0x0, 0x119bb6c, 0x6, 0xc000037bd0, 0xb, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:274 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc0001d0000, 0x1565240, 0xc000bd5b80, 0xc000240950, 0x154c0a0, 0xc000231520, 0xc000240bc0, 0x13979c0, 0xc000240bd0, 0x156afc0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:584 +0x334
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0001b4500, 0x13981c8, 0x1d, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/server/start.go:129 +0x4c1
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000443400, 0x1db18b0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/server/start.go:43 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000443400, 0x1db18b0, 0x0, 0x0, 0xc000443400, 0x1db18b0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00011c000, 0x11c0836, 0xc000bc9ea0, 0x5977b2)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00011c000, 0x13985e8, 0x11a6115, 0x10)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/libs/cli/setup.go:89 +0x3c
main.main()
	/root/gaia/cmd/gaiad/main.go:68 +0x875

root@cosmos-atom:#
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Seems like you're trying to run with the mainnet genesis/state? If so, please read [here](https://github.com/cosmos/gaia/issues/127#issuecomment-531765846).

**Comment by dev-lc** [comment]
> Seems like you're trying to run with the mainnet genesis/state? If so, please read [here](https://github.com/cosmos/gaia/issues/127#issuecomment-531765846).

Ok. Could you please provide the place, where I can obtain addresses to public remote full-nodes. What should I insert in this command:
`gaiacli config node <host>:<port>`

**Comment by alexanderbez** [comment]
You need to be running v0.34.7 and not v2.0.0

**Comment by w1t** [comment]
@alexanderbez I checked out cosmos-sdk v0.34.7 and follow the instruction 
https://cosmos.network/docs/cosmos-hub/installation.html#install-gaia

but t"make tools install" does not work as instructed
=No rule to make target `install'

Also the installation link is broken on the launch page.
https://github.com/cosmos/launch

Right now, no one can set up a Gaia node and connect to the main-net by following the instruction provided. 

Can you help to fix it?
