### ISSUE TITLE
Discussion if there is a potential bug in branch-theta-prepare

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1299]
## Version
on `theta-prepare` branch, if i overwrite the [fromVM (version map of modules)](https://github.com/cosmos/gaia/blob/9f23c11fcf8b93ea07ca08cdb62a300900f060a8/app/app.go#L655) to `fromVM[moduleName] = 1` , which means during upgrade, i force migrate all he modules from version 1 to some upgraded version with neglecting what this the present module version. 
then I tested theta-prepare branch by a local upgrade test from gaiad v6 -> gaiad build from `theta-prepare` with the above mentioned version map change.

during upgrade, I will have the following err:
```
applying upgrade "v07-Theta" at height: 26
7:51PM INF start to run module migrations...
7:51PM INF migrating module bank from version 1 to version 2
7:51PM INF migrating module distribution from version 1 to version 2
7:51PM INF migrating module staking from version 1 to version 2
7:51PM INF migrating module slashing from version 1 to version 2
7:51PM INF migrating module gov from version 1 to version 2
7:51PM INF migrating module ibc from version 1 to version 2
7:51PM INF created new capability module=ibc name=ports/icahost
7:51PM INF port binded module=x/ibc/port port=icahost
7:51PM INF claimed capability capability=2 module=icahost name=ports/icahost
7:51PM INF adding a new module: interchainaccounts
7:51PM INF migrating module liquidity from version 1 to version 2
7:51PM INF migrating module auth from version 1 to version 2
7:51PM ERR WARNING: Attempt to allocate proposer rewards to unknown proposer cosmosvalcons1qlg5qu9dpw4vf9ngthdq3p4rv3eeepgl0fkg55. This should happen only if the proposer unbonded completely within a single block, which generally should not happen except in exceptional circumstances (or fuzz testing). We recommend you investigate immediately. module=x/distribution
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x105e4c918]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.AllocateTokensToValidator({{0x1069c38c8, 0x1400143a490}, {0x106a188c8, 0x140011d7d10}, {{0x106a188c8, 0x140011d7d10}, 0x1400012b2f0, {0x1069c38c8, 0x1400143a4c0}, {0x1069c3918, ...}, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/x/distribution/keeper/allocation.go:107 +0x28
github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.AllocateTokens({{0x1069c38c8, 0x1400143a490}, {0x106a188c8, 0x140011d7d10}, {{0x106a188c8, 0x140011d7d10}, 0x1400012b2f0, {0x1069c38c8, 0x1400143a4c0}, {0x1069c3918, ...}, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/x/distribution/keeper/allocation.go:95 +0xe34
github.com/cosmos/cosmos-sdk/x/distribution.BeginBlocker({{0x1069f4f68, 0x140000580a8}, {0x106a1cf60, 0x14000542b00}, {{0xb, 0x0}, {0x1400057c8c0, 0x4}, 0x1a, {0x4f07720, ...}, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/x/distribution/abci.go:32 +0x1e8
github.com/cosmos/cosmos-sdk/x/distribution.AppModule.BeginBlock(...)
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/x/distribution/module.go:170
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0x1400131a180, {{0x1069f4f68, 0x140000580a8}, {0x106a1cf60, 0x14000542b00}, {{0xb, 0x0}, {0x1400057c8c0, 0x4}, 0x1a, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/types/module/module.go:479 +0x1c4
github.com/cosmos/gaia/v7/app.(*GaiaApp).BeginBlocker(...)
	/Users/yaruwang/code/gaia/app/app.go:727
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0x14001381a00, {{0x14000056ec0, 0x20, 0x20}, {{0xb, 0x0}, {0x1400057c8c0, 0x4}, 0x1a, {0x4f07720, ...}, ...}, ...})
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/baseapp/abci.go:194 +0x7fc
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0x14000cf9440, {{0x14000056ec0, 0x20, 0x20}, {{0xb, 0x0}, {0x1400057c8c0, 0x4}, 0x1a, {0x4f07720, ...}, ...}, ...})
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0x114
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0x14000de1570, {{0x14000056ec0, 0x20, 0x20}, {{0xb, 0x0}, {0x1400057c8c0, 0x4}, 0x1a, {0x4f07720, ...}, ...}, ...})
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x58
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x1069f5cc0, 0x1400060e660}, {0x106a08e90, 0x14000de1570}, 0x1400010e1e0, {0x106a16bf0, 0x14000de0960}, 0x1)
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x30c
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0x1400126a4d0, {{{0xb, 0x0}, {0x14000d76738, 0x8}}, {0x14000d76770, 0x4}, 0x1, 0x19, {{0x1400056a480, ...}, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0xfc
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0x140005e7dc0, {{{0xb, 0x0}, {0x14000d76738, 0x8}}, {0x14000d76770, 0x4}, 0x1, 0x19, {{0x1400056a480, ...}, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:503 +0x1a8
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0x140005e9dc0, {{{0xb, 0x0}, {0x14000d76738, 0x8}}, {0x14000d76770, 0x4}, 0x1, 0x19, {{0x1400056a480, ...}, ...}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:416 +0x6d0
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x140005e7dc0, {0x106a1e140, 0x140005c0340})
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x400
github.com/tendermint/tendermint/node.doHandshake({0x106a16bf0, 0x14000de0960}, {{{0xb, 0x0}, {0x14000d76738, 0x8}}, {0x14000d76770, 0x4}, 0x1, 0x19, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x114
github.com/tendermint/tendermint/node.NewNode(0x14001384140, {0x1069d32b8, 0x1400131fa40}, 0x14000de0a50, {0x1069b5b00, 0x140005a29c0}, 0x14000de0ae0, 0x10698f7a8, 0x14000de0bf0, {0x1069f5cc0, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x510
github.com/cosmos/cosmos-sdk/server.startInProcess(0x14001259de0, {{0x0, 0x0, 0x0}, {0x106a2afb8, 0x1400132e8a0}, {0x14001366040, 0x4}, {0x1069fe0c0, 0x140011d7d10}, ...}, ...)
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:263 +0x768
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0x14001275680, {0x14001259f20, 0x0, 0x2})
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:129 +0x144
github.com/spf13/cobra.(*Command).execute(0x14001275680, {0x14001259f00, 0x2, 0x2})
	/Users/yaruwang/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x140011bc780)
	/Users/yaruwang/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yaruwang/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/yaruwang/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x140011bc780, {0x140005abde8, 0x15})
	/Users/yaruwang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.1/server/cmd/execute.go:36 +0x23c
main.main()
	/Users/yaruwang/code/gaia/cmd/gaiad/main.go:16 +0x3c
```

so for theta upgrade, even though there is no module migration, only one new module `interchain accounts` is added, so i would not see the above err.

 but does the above err means if in the future we do a migration of some modules, the err will appear ? 

*Is it beginblocker module order problem ? the migration order should follow the module init genesis order ?*
I tried to change distribution module order but still get the same err.

## Steps to Reproduce
1. build gaiad v6.0.0 and init a chain.
2. check out `theta-prepare` branch and insert the following code in [line](https://github.com/cosmos/gaia/blob/9f23c11fcf8b93ea07ca08cdb62a300900f060a8/app/app.go#L657) 
```
                         fromVM = make(map[string]uint64)

			for moduleName, eachModule := range app.mm.Modules {
				fromVM[moduleName] = 1
			}
			delete(fromVM, icatypes.ModuleName)
```
build a new gaiad
3. test upgrade from v6.0.0 to the new gaiad.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by yaruwangway** [comment]
I am not sure this err is introduced by I force module to migrate from version 1, or because I have a potential bug.

**Comment by yaruwangway** [comment]
`distribution module` is ready in 2, fromVM =1 will make `distribution module` migrate twice from version 2 😂

**Comment by robert-zaremba** [comment]
This is because in 0.44 the x/distribution consensus version is set to 2 already. You are overwriting it and setting to 1, so the system thinks that it needs to do the migration 1->2 again.... which is breaking because it's adding prefixes ... so redoing doubling that migration the keys in state will change and you will not be able to read the records properly.

**Comment by yaruwangway** [comment]
thank you! @robert-zaremba
