### ISSUE TITLE
All files in config directory deleted

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/gaia#132]
I am running two nodes on gaia-3002. Today I tested @zmanian issue with not being able to use `gaia client query account xxx`. The queries worked. 

I left the computer, and later on I came back and found that gaia-3002 had halted. The node on which I ran `gaia client query account xxx` deleted all files in `~/.cosmos-gaia-cli`.

This is not the first time this has happed to me. This also happened on gaia-3000. I still don't know how to reproduce this, but two times my `priv_validator.json` got deleted.

Node IP: 165.227.246.236

```
E[02-18|16:20:03.161] Failed to add peer                           module=p2p address=159.89.15.116:46656 err="Ignoring connection from self"
E[02-18|16:20:03.183] Failed to add peer                           module=p2p address=35.204.86.158:46656 err="Duplicate peer"
I[02-18|16:20:07.818] Executed block                               module=state height=28889 validTxs=0 invalidTxs=0
I[02-18|16:20:07.825] Committed state                              module=state height=28889 txs=0 appHash=F113F6B8F2A131D7AB9AEBACAAF364886CC48C8F
I[02-18|16:20:16.391] Executed block                               module=state height=28890 validTxs=0 invalidTxs=0
I[02-18|16:20:16.394] Committed state                              module=state height=28890 txs=0 appHash=C80E5852E8FAB09E94B6A1D4B2929DCC1C00FD44
I[02-18|16:20:25.516] Executed block                               module=state height=28891 validTxs=0 invalidTxs=0
I[02-18|16:20:25.520] Committed state                              module=state height=28891 txs=0 appHash=96B8F3F4F2CC43BECCB012486C6B4CA951DD55BA
E[02-18|16:20:33.164] Failed to add peer                           module=p2p address=159.89.15.116:46656 err="Ignoring connection from self"
E[02-18|16:20:33.166] Failed to add peer                           module=p2p address=67.207.78.91:46656 err="Duplicate peer"
E[02-18|16:20:33.193] Failed to add peer                           module=p2p address=35.204.86.158:46656 err="Duplicate peer"
panic: open /home/avo/.cosmos-gaia-cli/data/cs.wal/wal: no such file or directory

goroutine 1096 [running]:
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile.(*Group).checkHeadSizeLimit(0xc4230c8d20)
        /home/avo/work/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile/group.go:213 +0xa9
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile.(*Group).processTicks(0xc4230c8d20)
        /home/avo/work/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile/group.go:195 +0x2d
created by github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile.(*Group).OnStart
        /home/avo/work/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/autofile/group.go:103 +0x41
avo@gaia-2:~/.cosmos-gaia-cli$ gaia node start
No genesis file at /home/avo/.cosmos-gaia-cli/genesis.json, skipping...
ERROR: Couldn't read GenesisDoc file: open /home/avo/.cosmos-gaia-cli/genesis.json: no such file or directory
avo@gaia-2:~/.cosmos-gaia-cli$ ls
avo@gaia-2:~/.cosmos-gaia-cli$ ls
avo@gaia-2:~/.cosmos-gaia-cli$ ls -al
total 0
avo@gaia-2:~/.cosmos-gaia-cli$ gaia node start
No genesis file at /home/avo/.cosmos-gaia-cli/genesis.json, skipping...
ERROR: Couldn't read GenesisDoc file: open /home/avo/.cosmos-gaia-cli/genesis.json: no such file or directory
avo@gaia-2:~/.cosmos-gaia-cli$
```

**Comment by zmanian** [comment]
A theory is this has  something to do with `gaia client` and `gaia node` sharing the same home directory.

**Comment by zmanian** [comment]
Additional thoughts. This comes from tendermint assuming it has exclusive control over a home directory and gaia assuming it also has exclusive control over it's home directory and deleting each others files.

**Comment by zramsay** [comment]
see #73

**Comment by zramsay** [comment]
https://github.com/cosmos/cosmos-sdk/issues/581
