### ISSUE TITLE
Runtime error after upgrading to v7.0.0

### ISSUE THREAD

**Issue by ciknight** [cosmos/gaia#1375]
## Summary of Bug
Gaia throws an exception when I upgrade Gaia to 7.0.0.
> panic: runtime error: invalid memory address or nil pointer dereference

Verbose output
```
2:35AM INF starting ABCI with Tendermint
2:35AM INF Starting multiAppConn service impl=multiAppConn module=proxy
2:35AM INF Starting localClient service connection=query impl=localClient module=abci-client
2:35AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
2:35AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
2:35AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
2:35AM INF Starting EventBus service impl=EventBus module=events
2:35AM INF Starting PubSub service impl=PubSub module=pubsub
2:35AM INF Starting IndexerService service impl=IndexerService module=txindex
2:35AM INF ABCI Handshake App Info hash="��]��t��\x1eԞ��`��'�Ņ]\x00����~���,�" height=9953290 module=consensus protocol-version=0 software-version=v7.0.0
2:35AM INF ABCI Replay Blocks appHeight=9953290 module=consensus stateHeight=9953290 storeHeight=9953290
2:35AM INF Completed ABCI Handshake - Tendermint and App are synced appHash="��]��t��\x1eԞ��`��'�Ņ]\x00����~���,�" appHeight=9953290 module=consensus
2:35AM INF Version info block=11 p2p=8 tendermint_version=v0.34.14
2:35AM INF This node is not a validator addr=F237A53DFD82862FDD03A40AE5A0CD65AD1187D9 module=consensus pubKey=NAL3H+lrpi8jo7yNOBGwkITyBO1y7w6bCnALBpPWjg4=
2:35AM INF P2P Node ID ID=e8d549a41a7041a62a788addc03338d68260a04a file=/root/.gaia/config/node_key.json module=p2p
2:35AM INF Adding persistent peers addrs=[] module=p2p
2:35AM INF Adding unconditional peer ids ids=[] module=p2p
2:35AM INF Add our address to book addr={"id":"e8d549a41a7041a62a788addc03338d68260a04a","ip":"0.0.0.0","port":26656} book=/root/.gaia/config/addrbook.json module=p2p
2:35AM INF Starting Node service impl=Node
2:35AM INF Starting pprof server laddr=localhost:6060
2:35AM INF Starting RPC HTTP server on 127.0.0.1:26657 module=rpc-server
2:35AM INF Starting P2P Switch service impl="P2P Switch" module=p2p
2:35AM INF Starting PEX service impl=PEX module=pex
2:35AM INF Starting AddrBook service book=/root/.gaia/config/addrbook.json impl=AddrBook module=p2p
2:35AM INF Starting Mempool service impl=Mempool module=mempool
2:35AM INF Starting BlockchainReactor service impl=BlockchainReactor module=blockchain
2:35AM INF Starting BlockPool service impl=BlockPool module=blockchain
2:35AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
2:35AM INF Will dial address addr={"id":"b9b88b86b3015b41568ed532faeff1f120d3f91b","ip":"35.204.75.215","port":26656} module=pex
2:35AM INF Will dial address addr={"id":"cbd79ed2b90092b84c8d0bffb7604b3c7756798a","ip":"95.216.1.108","port":26656} module=pex
2:35AM INF Dialing peer address={"id":"457533c6db6d9edf4e0f6791d11d89925ab4f9ee","ip":"52.59.228.64","port":26656} module=p2p
2:35AM INF Starting Consensus service impl=ConsensusReactor module=consensus
2:35AM INF Reactor  module=consensus waitSync=true
2:35AM INF Starting Evidence service impl=Evidence module=evidence
2:35AM INF Dialing peer address={"id":"bae722640449e0b622404f30c48f251f642fa677","ip":"34.222.79.47","port":31675} module=p2p
2:35AM INF Dialing peer address={"id":"bf8328b66dceb4987e5cd94430af66045e59899f","ip":"159.203.104.207","port":26656} module=p2p
2:35AM INF Dialing peer address={"id":"b9b88b86b3015b41568ed532faeff1f120d3f91b","ip":"35.204.75.215","port":26656} module=p2p
2:35AM INF Dialing peer address={"id":"cbd79ed2b90092b84c8d0bffb7604b3c7756798a","ip":"95.216.1.108","port":26656} module=p2p
2:35AM INF Starting StateSync service impl=StateSync module=statesync
2:35AM INF Saving AddrBook to file book=/root/.gaia/config/addrbook.json module=p2p size=1149
2:35AM INF Starting Peer service impl="Peer{MConn{104.248.211.206:26656} 7f81f644eae328219cf1ab2d61218230b421cf2c out}" module=p2p peer={"id":"7f81f644eae328219cf1ab2d61218230b421cf2c","ip":"104.248.211.2
06","port":26656}
2:35AM INF Starting MConnection service impl=MConn{104.248.211.206:26656} module=p2p peer={"id":"7f81f644eae328219cf1ab2d61218230b421cf2c","ip":"104.248.211.206","port":26656}
2:35AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
2:35AM ERR dialing failed (attempts: 1): dial tcp 51.79.77.6:26656: connect: connection refused addr={"id":"35b1b109d8510f668f0440f4be998572f1f1ad86","ip":"51.79.77.6","port":26656} module=pex
2:35AM INF Starting Peer service impl="Peer{MConn{34.222.79.47:31675} bae722640449e0b622404f30c48f251f642fa677 out}" module=p2p peer={"id":"bae722640449e0b622404f30c48f251f642fa677","ip":"34.222.79.47","p
ort":31675}
2:35AM INF Starting MConnection service impl=MConn{34.222.79.47:31675} module=p2p peer={"id":"bae722640449e0b622404f30c48f251f642fa677","ip":"34.222.79.47","port":31675}
2:35AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
2:35AM ERR dialing failed (attempts: 1): dial tcp 51.210.217.48:26656: connect: connection refused addr={"id":"e3af52991ad9fa5c0f89a2528045f7bdcc366953","ip":"51.210.217.48","port":26656} module=pex
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16916f3]

goroutine 73 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc000f2c3f1, 0xb}, 0xc00121dd10, {0x2020550, 0xc00129af80}, {0x207a538, 0xc000f508c0}, 0xc00129f7d0, {0x20106c0, 0xc000e3f380}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/abci.go:38 +0x1093
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2053188, 0xc00012c000}, {0x207fc60, 0xc004540380}, {{0xb, 0x0}, {0xc001a12110, 0xb}, 0x97e00b, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.1/types/module/module.go:479 +0x218
github.com/cosmos/gaia/v7/app.(*GaiaApp).BeginBlocker(...)
        github.com/cosmos/gaia/v7/app/app.go:707
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc00300ada0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001a12110, 0xb}, 0x97e00b, {0x33ddaa46, ...}, ...}, ...})
        github.com/cosmos/cosmos-sdk@v0.45.1/baseapp/abci.go:194 +0x9dc
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00300ada0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001a12110, 0xb}, 0x97e00b, {0x33ddaa46, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00300ada0, 0x20, 0x20}, {{0xb, 0x0}, {0xc001a12110, 0xb}, 0x97e00b, {0x33ddaa46, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2053ee0, 0xc000ef9bc0}, {0x2068e50, 0xc000e34950}, 0xc00000b4a0, {0x2078078, 0xc0027fdb10}, 0x97e00a)
        github.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc001a12f30, 0x8}}, {0xc001a12f40, 0xb}, 0x4f5b97, 0x97e00a, {{0xc0031ead60, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00015d180, 0x0)
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:398 +0xb7b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x85
```

## Version
```
root@51fdd550f8f4:/# gaiad version
v7.0.0
```

## Steps to Reproduce
```
git clone https://github.com/cosmos/gaia --depth 1 --branch v7.0.0 && \
    cd gaia && LDFLAGS="" CGO_ENABLED=0 make install

gaiad init mymoniker && wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz && \
    gzip -d genesis.cosmoshub-4.json.gz && \
    mv genesis.cosmoshub-4.json /root/.gaia/config/genesis.json && \
    curl https://quicksync.io/addrbook.cosmos.json > /root/.gaia/config/addrbook.json

sed -i'' 's/minimum-gas-prices = ""/minimum-gas-prices = "0.0025uatom"/' /root/.gaia/config/app.toml
```
# quick sync

```
cd /root/.gaia && export URL=`curl https://quicksync.io/cosmos.json|jq -r '.[] |select(.file=="cosmoshub-4-pruned")|.url'` && \
    aria2c -x5 $(URL) && lz4 -c -d `basename $(URL)` | tar xf -
```

# run

```
gaiad start --x-crisis-skip-assert-invariants
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @ciknight the upgrade to V7 Theta hasn't happened yet...check the [current upgrade proposal](https://www.mintscan.io/cosmos/proposals/65) on mintscan and the [current release notes](https://github.com/cosmos/gaia/releases/tag/v7.0.0) for v7-theta for more information. Also I'm not sure which instructions you're following but if you opt to use quicksync.io then you don't need to run `gaiad init` or download the genesis. 

Right now to sync a node to mainnet, make sure to build [`v6.0.4`](https://github.com/cosmos/gaia/releases/tag/v6.0.4)

**Comment by ciknight** [comment]
> Hi @ciknight the upgrade to V7 Theta hasn't happened yet...check the [current upgrade proposal](https://www.mintscan.io/cosmos/proposals/65) on mintscan and the [current release notes](https://github.com/cosmos/gaia/releases/tag/v7.0.0) for v7-theta for more information. Also I'm not sure which instructions you're following but if you opt to use quicksync.io then you don't need to run `gaiad init` or download the genesis.
> 
> Right now to sync a node to mainnet, make sure to build [`v6.0.4`](https://github.com/cosmos/gaia/releases/tag/v6.0.4)

Okay, thanks.
