### ISSUE TITLE
Upgrade 7.0.0 from 6.0.0, but gaiad can not start

### ISSUE THREAD

**Issue by lcgogo** [cosmos/gaia#1380]
## Summary of Bug

7.0.0 can not start from 6.0.0 data

## Version

```shell
$ gaiad version --long
name: gaia
server_name: gaiad
version: v7.0.0
commit: 79fcf71689358b6212ae91f41070de9669421cf5
build_tags: netgo,
go: go version go1.15.13 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6
- github.com/ChainSafe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d
- github.com/Workiva/go-datastructures@v1.0.52
- github.com/armon/go-metrics@v0.3.10
- github.com/beorn7/perks@v1.0.1
- github.com/bgentry/speakeasy@v0.1.0
- github.com/btcsuite/btcd@v0.22.0-beta
- github.com/cespare/xxhash/v2@v2.1.2
- github.com/coinbase/rosetta-sdk-go@v0.7.0
- github.com/confio/ics23/go@v0.7.0
- github.com/cosmos/btcutil@v1.0.4
- github.com/cosmos/cosmos-sdk@v0.45.1
- github.com/cosmos/go-bip39@v1.0.0
- github.com/cosmos/iavl@v0.17.3
- github.com/cosmos/ibc-go/v3@v3.0.0
- github.com/davecgh/go-spew@v1.1.1
- github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f
- github.com/dvsekhvalnov/jose2go@v0.0.0-20200901110807-248326c1351b
- github.com/felixge/httpsnoop@v1.0.1
- github.com/fsnotify/fsnotify@v1.5.1
- github.com/go-kit/kit@v0.10.0
- github.com/go-logfmt/logfmt@v0.5.0
- github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2
- github.com/gogo/gateway@v1.1.0
- github.com/gogo/protobuf@v1.3.3 => github.com/regen-network/protobuf@v1.3.3-alpha.regen.1
- github.com/golang/protobuf@v1.5.2
- github.com/golang/snappy@v0.0.3
- github.com/google/btree@v1.0.0
- github.com/google/orderedcode@v0.0.1
- github.com/gorilla/handlers@v1.5.1
- github.com/gorilla/mux@v1.8.0
- github.com/gorilla/websocket@v1.4.2
- github.com/gravity-devs/liquidity@v1.5.0
- github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0
- github.com/grpc-ecosystem/grpc-gateway@v1.16.0
- github.com/grpc-ecosystem/grpc-gateway/v2@v2.0.1
- github.com/gsterjov/go-libsecret@v0.0.0-20161001094733-a6f4afe4910c
- github.com/gtank/merlin@v0.1.1
- github.com/gtank/ristretto255@v0.1.2
- github.com/hashicorp/go-immutable-radix@v1.3.1
- github.com/hashicorp/golang-lru@v0.5.4
- github.com/hashicorp/hcl@v1.0.0
- github.com/hdevalence/ed25519consensus@v0.0.0-20210204194344-59a8610d2b87
- github.com/improbable-eng/grpc-web@v0.14.1
- github.com/klauspost/compress@v1.11.7
- github.com/lib/pq@v1.10.2
- github.com/libp2p/go-buffer-pool@v0.0.2
- github.com/magiconair/properties@v1.8.5
- github.com/mattn/go-isatty@v0.0.14
- github.com/matttproud/golang_protobuf_extensions@v1.0.1
- github.com/mimoo/StrobeGo@v0.0.0-20181016162300-f8f6d4d2b643
- github.com/minio/highwayhash@v1.0.1
- github.com/mitchellh/go-homedir@v1.1.0
- github.com/mitchellh/mapstructure@v1.4.3
- github.com/mtibben/percent@v0.2.1
- github.com/pelletier/go-toml@v1.9.4
- github.com/pkg/errors@v0.9.1
- github.com/pmezard/go-difflib@v1.0.0
- github.com/prometheus/client_golang@v1.11.0
- github.com/prometheus/client_model@v0.2.0
- github.com/prometheus/common@v0.29.0
- github.com/prometheus/procfs@v0.6.0
- github.com/rakyll/statik@v0.1.7
- github.com/rcrowley/go-metrics@v0.0.0-20200313005456-10cdbea86bc0
- github.com/regen-network/cosmos-proto@v0.3.1
- github.com/rs/cors@v1.7.0
- github.com/rs/zerolog@v1.23.0
- github.com/spf13/afero@v1.6.0
- github.com/spf13/cast@v1.4.1
- github.com/spf13/cobra@v1.3.0
- github.com/spf13/jwalterweatherman@v1.1.0
- github.com/spf13/pflag@v1.0.5
- github.com/spf13/viper@v1.10.1
- github.com/strangelove-ventures/packet-forward-middleware/v2@v2.1.1
- github.com/stretchr/testify@v1.7.0
- github.com/subosito/gotenv@v1.2.0
- github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca
- github.com/tendermint/btcd@v0.1.1
- github.com/tendermint/crypto@v0.0.0-20191022145703-50d29ede1e15
- github.com/tendermint/go-amino@v0.16.0
- github.com/tendermint/tendermint@v0.34.14
- github.com/tendermint/tm-db@v0.6.4
- golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5
- golang.org/x/net@v0.0.0-20210903162142-ad29c8ab022f
- golang.org/x/sys@v0.0.0-20211210111614-af8b64212486
- golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
- golang.org/x/text@v0.3.7
- google.golang.org/genproto@v0.0.0-20211208223120-3a66f561d7aa
- google.golang.org/grpc@v1.44.0 => google.golang.org/grpc@v1.33.2
- google.golang.org/protobuf@v1.27.1
- gopkg.in/ini.v1@v1.66.2
- gopkg.in/yaml.v2@v2.4.0
- gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b
- nhooyr.io/websocket@v1.8.6
cosmos_sdk_version: v0.45.1
```

## Steps to Reproduce

```shell
6:12AM INF Starting multiAppConn service impl=multiAppConn module=proxy
6:12AM INF Starting localClient service connection=query impl=localClient module=abci-client
6:12AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
6:12AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
6:12AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
6:12AM INF Starting EventBus service impl=EventBus module=events
6:12AM INF Starting PubSub service impl=PubSub module=pubsub
6:12AM INF Starting IndexerService service impl=IndexerService module=txindex
6:12AM INF ABCI Handshake App Info hash="Mfg�K~�'n�\x13\\�\"�r�\u007f\x19\x1aQ�\x1a2eE}遴y�" height=9979330 module=consensus protocol-version=0 software-version=v7.0.0
6:12AM INF ABCI Replay Blocks appHeight=9979330 module=consensus stateHeight=9979330 storeHeight=9979331
6:12AM INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19e1748]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker(0x7ffc58a2ff48, 0xa, 0xc003116b40, 0x2422a20, 0xc0005d04c0, 0x245f340, 0xc0012a8360, 0xc0005d4db0, 0x23fe920, 0xc000e9aea0, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/abci.go:38 +0x12c8
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000278300, 0x2447380, 0xc000056050, 0x24621c0, 0xc00839bec0, 0xb, 0x0, 0xc0c3705640, 0xb, 0x9845c3, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/types/module/module.go:479 +0x1f8
github.com/cosmos/gaia/v7/app.(*GaiaApp).BeginBlocker(...)
	github.com/cosmos/gaia/v7/app/app.go:707
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000e9aea0, 0xc0c3807420, 0x20, 0x20, 0xb, 0x0, 0xc0c3705640, 0xb, 0x9845c3, 0x137dbe1f, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/baseapp/abci.go:194 +0x89b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000245ce0, 0xc0c3807420, 0x20, 0x20, 0xb, 0x0, 0xc0c3705640, 0xb, 0x9845c3, 0x137dbe1f, ...)
	github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0xfa
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc009cd1d00, 0xc0c3807420, 0x20, 0x20, 0xb, 0x0, 0xc0c3705640, 0xb, 0x9845c3, 0x137dbe1f, ...)
	github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x75
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x2448280, 0xc001202b40, 0x2455880, 0xc009cd1d00, 0xc001000b40, 0x245eec0, 0xc009ad8bb0, 0x4f5b97, 0xc00882b020, 0x20, ...)
	github.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x51b
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc014534af0, 0xb, 0x0, 0x0, 0x0, 0xc009ad79c0, 0xb, 0x4f5b97, 0x9845c2, 0xc00882b020, ...)
	github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x165
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0c381dba0, 0xb, 0x0, 0x0, 0x0, 0xc009ad79c0, 0xb, 0x4f5b97, 0x9845c2, 0xc00882b020, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:503 +0x292
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc01248dba0, 0xb, 0x0, 0x0, 0x0, 0xc009ad79c0, 0xb, 0x4f5b97, 0x9845c2, 0xc00882b020, ...)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:416 +0xdb8
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0c381dba0, 0x2463680, 0xc0013316c0, 0x1, 0x1)
	github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x478
github.com/tendermint/tendermint/node.doHandshake(0x245eec0, 0xc009ad8bb0, 0xb, 0x0, 0x0, 0x0, 0xc009ad79c0, 0xb, 0x4f5b97, 0x9845c2, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0012b72c0, 0x243d880, 0xc000d7ca00, 0xc0033cef10, 0x23ffac0, 0xc01052e000, 0xc0033cefa0, 0x21ef4d8, 0xc0033cf090, 0x2448280, ...)
	github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x20a5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0012fd5c0, 0x0, 0x0, 0x0, 0x246f140, 0xc0013e66f0, 0x0, 0x0, 0x2451aa0, 0xc0012a8360, ...)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:263 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012e8f00, 0xc001351bf0, 0x0, 0x3, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:129 +0x1ec
github.com/spf13/cobra.(*Command).execute(0xc0012e8f00, 0xc0012c9f80, 0x3, 0x4, 0xc0012e8f00, 0xc0012c9f80)
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0012d8000, 0x0, 0x0, 0xc0012a40c0)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.3.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc0012d8000, 0xc0012a40c0, 0x6, 0x2465980, 0xc0012a8360)
	github.com/cosmos/cosmos-sdk@v0.45.1/server/cmd/execute.go:36 +0x285
main.main()
	github.com/cosmos/gaia/v7/cmd/gaiad/main.go:16 +0x45
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @lcgogo, the upgrade to `v7.0.0` hasn't happened yet, according to the [release notes](https://github.com/cosmos/gaia/releases/tag/v7.0.0), it's scheduled to happen on April 12th around 12:00:00 UTC. You can also check the [upgrade proposal](https://www.mintscan.io/cosmos/proposals/65) on mintscan for more information.

**Comment by lcgogo** [comment]
> Hi @lcgogo, the upgrade to `v7.0.0` hasn't happened yet, according to the [release notes](https://github.com/cosmos/gaia/releases/tag/v7.0.0), it's scheduled to happen on April 12th around 12:00:00 UTC. You can also check the [upgrade proposal](https://www.mintscan.io/cosmos/proposals/65) on mintscan for more information.

many thanks.
