### ISSUE TITLE
Upgrade 6.0.4 -> 7.0.0 : Nil pointer dereference on startup

### ISSUE THREAD

**Issue by vbergeron-ledger** [cosmos/gaia#1383]
## Summary of Bug

When starting gaiad node using the 7.0.0 binaries on a up-to-date 6.0.4 database, I experience a Nil pointer dereference issue imediatly after startup.

here is the detail of the stacktrace 
```
bSub","time":"2022-04-05T11:48:03Z","message":"Starting PubSub service"}
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: {"level":"info","module":"txindex","impl":"IndexerService","time":"2022-04-05T11:48:07Z","message":"Starting IndexerService service"}
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: {"level":"info","module":"consensus","hash":"\ufffd\u0004J8\ufffd\ufffd\ufffdO\ufffd\u0018\ufffd\ufffd,z\ufffdK\ufffd\ufffd\ufffd*;j\ufffd\ufffd\\\ufffdϼ\ufffd\ufffd\ufffd$","height":9917513,"protocol-version":0,"software-version":"v7.0.0","time":"2022-04-05T11:48:07Z","message":"ABCI Handshake App Info"}
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: {"level":"info","module":"consensus","appHeight":9917513,"stateHeight":9917513,"storeHeight":9917514,"time":"2022-04-05T11:48:07Z","message":"ABCI Replay Blocks"}
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: {"level":"info","module":"consensus","time":"2022-04-05T11:48:07Z","message":"Replay last block using real app"}
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x169d7b3]
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: goroutine 1 [running]:
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7ffcbac79ef9, 0xc}, 0xc007ac9740, {0x203b6d0, 0xc007af9ed0}, {0x2095a98, 0xc001272570}, 0xc007b0f0b0, {0x202b860, 0xc000e1bba0}, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/abci.go:38 +0x1093
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/cosmos-sdk@v0.45.1/x/upgrade/module.go:130
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x206e568, 0xc0001b6000}, {0x209b1c0, 0xc00c6a3200}, {{0xb, 0x0}, {0xc0b5ff9cf0, 0xb}, 0x97544a, ...}, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/cosmos-sdk@v0.45.1/types/module/module.go:479 +0x218
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/gaia/v7/app.(*GaiaApp).BeginBlocker(...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/gaia/v7/app/app.go:707 
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0b61629e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0b5ff9cf0, 0xb}, 0x97544a, {0x29eb3635, ...}, ...}, ...})
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/cosmos-sdk@v0.45.1/baseapp/abci.go:194 +0x9dc
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0b61629e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0b5ff9cf0, 0xb}, 0x97544a, {0x29eb3635, ...}, ...}, ...})
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:280 +0x118
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0b61629e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0b5ff9cf0, 0xb}, 0x97544a, {0x29eb3635, ...}, ...}, ...})
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:81 +0x55
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x206f2f8, 0xc0011f2ba0}, {0x2084330, 0xc007b3fdd0}, 0xc00000c5a0, {0x2093558, 0xc00e23c930}, 0x975449) 
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/state/execution.go:307 +0x3dd
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc00ba3d9a0, 0x7}}, {0xc00ba3d9b0, 0xb}, 0x4f5b97, 0x975449, {{0xc008286240, ...}, ...}, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/state/execution.go:140 +0x171
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc00ba3d9a0, 0x7}}, {0xc00ba3d9b0, 0xb}, 0x4f5b97, 0x975449, {{0xc008286240, ...}, ...}, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:503 +0x23c
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc00ba3d9a0, 0x7}}, {0xc00ba3d9b0, 0xb}, 0x4f5b97, 0x975449, {{0xc008286240, ...}, ...}, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:416 +0x7ae
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0b6179e58, {0x209c6a0, 0xc00e27e0d0})
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc00ba3d9a0, 0x7}}, {0xc00ba3d9b0, 0xb}, 0x4f5b97, 0x975449, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/tendermint/tendermint/node.NewNode(0xc0013b0140, {0x204b180, 0xc0005afd60}, 0xc007b3e810, {0x202ca20, 0xc00827fa10}, 0x0, 0x0, 0xc007b3eb20, {0x206f2f8, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x20ad0b8, 0xc001358fc0}, {0x0, 0x0}, {0x2077ad0, 0xc001272570}, ...}, ...)
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:263 +0x7c5
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012b4780, {0xc00128dee0, 0x0, 0x2})
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/cosmos/cosmos-sdk@v0.45.1/server/start.go:129 +0x193
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]: github.com/spf13/cobra.(*Command).execute(0xc0012b4780, {0xc00128dec0, 0x2, 0x2})
Apr 05 11:48:07 HOST_REDACTED cosmos[2687819]:         github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
```

## Version

`v7.0.0`

## Steps to Reproduce

Starting gaiad node using the 7.0.0 binaries on a up-to-date 6.0.4 database.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @vbergeron-ledger , the upgrade to `v7.0.0` hasn't happened yet, according to the [release notes](https://github.com/cosmos/gaia/releases/tag/v7.0.0), it's scheduled to happen on April 12th around 12:00:00 UTC. You can also check the [upgrade proposal](https://www.mintscan.io/cosmos/proposals/65) on mintscan for more information.

**Comment by vbergeron-ledger** [comment]
Idea, maybe having a segfault is not the nicest thing to throw at users in this case. What about having a error message ? :)
Not criticizing the way the upgrades are handled,  but it is kind of surprising that we have to wait until we reach the fork block to update.
This could be smoother for the user base.

**Comment by okwme** [comment]
thanks for the feedback @vbergeron-ledger it's an interesting suggestion!

we're currently working on the premise that the gaia codebase is theoretically untethered to the actual network in operation (for instance we have a tutorial where you can start running your own local version of the cosmos hub). This is how all Cosmos SDK apps currently work.

if we were to hardcode network versions to the binaries it would mean trying to run a version of gaia that isn't interacting with the one real live network would need extra flags.

In theory we could:
* add some sort of check so that if you try to run gaia v7 with any other genesis file than the cosmoshub-4 it would throw an error
* add some sort of a check so that if you were trying to run gaia v7 with a block height before the proposal height it would throw an error

This would mean that the binary we propose for each upgrade would need to already have the block height included in the code before we make the proposal (not impossible but needs to be coordinated)

then we'd need to add flags so that you could override these errors in case you were trying to run gaia as a local instance for testing or if you were running it as part of a public testnet (which we keep running all the time)

all possible but to be honest at the moment in terms of work and resources these changes would be classified as "nice to haves" as it would certainly improve some of the user experience (and cut down on our support requests 😉) but in light of other work on the table right now it would likely not get addressed in the next quarter.

I'm going to add "UX" and "nice to have" tags but for now will close the issue. I don't mean to diminish the pain from your user experience and appreciate that you've notified us of it but can't commit to a timeline of when it would be addressed at this point.

Thanks for your contribution!
