### ISSUE TITLE
insufficient fees err log for gaia rho branch (main)

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1534]
## Summary of Bug
when submitting transactions without enough fees, get 
` panic: value method github.com/cosmos/cosmos-sdk/types.TxResponse.UnpackInterfaces called using nil *TxResponse pointer
`

This shouldnot happen, the errlog should be `insufficient fees`.

## Steps to Reproduce
1. init a node with gaia main branch
2. submit tx with fees lower than min_gas_price required
3. check the err log

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
I get the same err with simd 0.46-rc1, but not sure if this is reproducible by others.

**Comment by yaruwangway** [comment]
Pull branch from main
build using make install
init a single validator chain .
change minimum-gas-prices = "1stake"   in app.toml
start chain gaiad start --mode validator`
do gaiad tx bank send --gas-prices 1stake ,  gaiad tx bank send --gas-prices 0.5stake , or gaiad tx bank send


init a single val node [script](https://github.com/cosmos/hub-eng/blob/main/tools/testing/scripts/localnet/configure_chains.sh)
you can also init yourself , should not influence the result. 
@tokamak-git

**Comment by okwme** [comment]
This seems to only be the case when broadcast mode is set to `block`.
We should confirm this is the case with simapp on the SDK and if so open an issue there.

**Comment by yaruwangway** [comment]
This blocks e2e tests for failed cases.

**Comment by yaruwangway** [comment]
more logs
```
panic: value method github.com/cosmos/cosmos-sdk/types.TxResponse.UnpackInterfaces called using nil *TxResponse pointer

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types.(*TxResponse).UnpackInterfaces(0xffffeed6ff2f?, {0x2776d78?, 0x4000cd00f0?})
	<autogenerated>:1 +0xb8
github.com/cosmos/cosmos-sdk/codec/types.UnpackInterfaces(...)
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/codec/types/interface_registry.go:275
github.com/cosmos/cosmos-sdk/codec.ProtoMarshalJSON({0x277ee60?, 0x0}, {0xffff7d668298, 0x400012e0f0})
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/codec/json.go:23 +0xec
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MarshalJSON(0x400016ac20, {0x277ee60?, 0x0})
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/codec/proto_codec.go:141 +0xec
github.com/cosmos/cosmos-sdk/client.Context.PrintProto({{0x4000b57650, 0x14, 0x18}, {0x27b0328, 0x4000ab5200}, 0x0, {0xffffeed6fee6, 0xc}, {0x27aa7b0, 0x400016ac20}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/client/context.go:291 +0x48
github.com/cosmos/cosmos-sdk/client/tx.BroadcastTx({{0x4000b57650, 0x14, 0x18}, {0x27b0328, 0x4000ab5200}, 0x0, {0xffffeed6fee6, 0xc}, {0x27aa7b0, 0x400016ac20}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/client/tx/tx.go:125 +0x550
github.com/cosmos/cosmos-sdk/client/tx.GenerateOrBroadcastTxWithFactory({{0x4000b57650, 0x14, 0x18}, {0x27b0328, 0x4000ab5200}, 0x0, {0xffffeed6fee6, 0xc}, {0x27aa7b0, 0x400016ac20}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/client/tx/tx.go:59 +0xd4
github.com/cosmos/cosmos-sdk/client/tx.GenerateOrBroadcastTxCLI({{0x4000b57650, 0x14, 0x18}, {0x27b0328, 0x4000ab5200}, 0x0, {0xffffeed6fee6, 0xc}, {0x27aa7b0, 0x400016ac20}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/client/tx/tx.go:29 +0xb4
github.com/cosmos/cosmos-sdk/x/bank/client/cli.NewSendTxCmd.func1(0x4000a78000?, {0x40004d6fc0, 0x3, 0x9?})
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/x/bank/client/cli/tx.go:64 +0x1d4
github.com/spf13/cobra.(*Command).execute(0x4000a78000, {0x40004d6f30, 0x9, 0x9})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x400098c000)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x60?, {0x0, 0x0}, {0x400016e7c0, 0xb})
	github.com/cosmos/cosmos-sdk@v0.46.0-rc1.0.20220616181117-53d0cc919f1a/server/cmd/execute.go:36 +0x1a8
main.main()
	github.com/cosmos/gaia/v8/cmd/gaiad/main.go:16 +0x44
```

**Comment by mmulji-ic** [comment]
@yaruwangway can you retest with block mode, otherwise raise an issue with SDK folks!

**Comment by yaruwangway** [comment]
This is solved by bumping to sdk .46.0, broadcast-mode block and sync both show correct err log of insufficient fees when not paying enough fees.
