### ISSUE TITLE
run 8.0.0 in docker meets panic: runtime error

### ISSUE THREAD

**Issue by lcgogo** [cosmos/gaia#2159]
I build gaia 8.0.0 based by golang:1.18-alpine3.17 dockerhub images

BTW: Images builded by version 7.1.0 and before were working fine.

```dockerfile
RUN mkdir -p /go/src/github.com/$${COIN_NAME} \
    && cd /go/src/github.com/$${COIN_NAME} \
    && git clone $${REPO_URL} \
    && cd gaia \
    && if [ "$${COIN_VERSION}" == "latest" ]; then \
         git checkout master; \
       else \
         git checkout v$${COIN_VERSION}; \
       fi \
#    && git apply /go/$${COIN_NAME}.patch \
    && make build-linux
```

But met followed issue

## Summary of Bug

```
7:29AM INF starting node with ABCI Tendermint in-process
7:30AM INF service start impl=multiAppConn module=proxy msg={}
7:30AM INF service start connection=query impl=localClient module=abci-client msg={}
7:30AM INF service start connection=snapshot impl=localClient module=abci-client msg={}
7:30AM INF service start connection=mempool impl=localClient module=abci-client msg={}
7:30AM INF service start connection=consensus impl=localClient module=abci-client msg={}
7:30AM INF service start impl=EventBus module=events msg={}
7:30AM INF service start impl=PubSub module=pubsub msg={}
7:31AM INF service start impl=IndexerService module=txindex msg={}
7:31AM INF ABCI Handshake App Info hash=".\u05cdSrp�(��^�N�\x10�N�{^��bn�K��T��\a" height=13980914 module=consensus protocol-version=0 software-version=v8.0.0
7:31AM INF ABCI Replay Blocks appHeight=13980914 module=consensus stateHeight=13980914 storeHeight=13980915
7:31AM INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x156c98d]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7ffd54347f48, 0xa}, 0xc0107ab680, {0x253b638, 0xc0108278f0}, {0x255a6b0, 0xc00125dad0}, 0xc010838ed0, {0x2535420, 0xc000694540}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/upgrade/abci.go:38 +0x100d
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x254e988, 0xc000056028}, {0x255a128, 0xc00ba07400}, {{0xb, 0x0}, {0xc1d6bded50, 0xb}, 0xd554f3, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/types/module/module.go:491 +0x3bb
github.com/cosmos/gaia/v8/app.(*GaiaApp).BeginBlocker(_, {{0x254e988, 0xc000056028}, {0x255a128, 0xc00ba07400}, {{0xb, 0x0}, {0xc1d6bded50, 0xb}, 0xd554f3, ...}, ...}, ...)
	github.com/cosmos/gaia/v8/app/app.go:243 +0x85
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc1d6ce9160, 0x20, 0x20}, {{0xb, 0x0}, {0xc1d6bded50, 0xb}, 0xd554f3, {0x233d81b7, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.12/baseapp/abci.go:177 +0x97c
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc1d6ce9160, 0x20, 0x20}, {{0xb, 0x0}, {0xc1d6bded50, 0xb}, 0xd554f3, {0x233d81b7, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc1d6ce9160, 0x20, 0x20}, {{0xb, 0x0}, {0xc1d6bded50, 0xb}, 0xd554f3, {0x233d81b7, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x254f788?, 0xc001247e00}, {0x2555008, 0xc017049e60}, 0xc0000010e0, {0x255b948, 0xc02c866198}, 0xd554f2?)
	github.com/tendermint/tendermint@v0.34.24/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc01733f990, 0xb}, 0x4f5b97, 0xd554f2, {{0xc01dc34260, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc01733f990, 0xb}, 0x4f5b97, 0xd554f2, {{0xc01dc34260, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc01733f990, 0xb}, 0x4f5b97, 0xd554f2, {{0xc01dc34260, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc1c6149e70, {0x255c7e8, 0xc0013361a0})
	github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc01733f990, 0xb}, 0x4f5b97, 0xd554f2, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0012ab400, {0x254b6b0, 0xc000178fa0}, 0xc01085ce70, {0x2536760, 0xc01a026a20}, 0x0?, 0x0?, 0xc01085d0a0, {0x254f788, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/node/node.go:777 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2562fe0, 0xc0013a8510}, {0x0, 0x0}, {0x2552de8, 0xc00125dad0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/server/start.go:280 +0x81b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012d4900?, {0xc00133ff50?, 0x0?, 0x3?})
	github.com/cosmos/cosmos-sdk@v0.45.12/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0012d4900, {0xc0012ff4c0, 0x3, 0x4})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00117ec00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc001255550, 0x6})
	github.com/cosmos/cosmos-sdk@v0.45.12/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/cosmos/gaia/v8/cmd/gaiad/main.go:16 +0x2c
```

## Version

/usr/bin/gaiad --home /data/atom version
v8.0.0

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by yaruwangway** [comment]
Hi @lcgogo, are you trying to join in mainnet ? mainnet is not on v8 yet. [Rho-testnet is using v8](https://github.com/cosmos/testnets/tree/master/public)

**Comment by glnro** [comment]
Hi @lcgogo `v8` requires an upgrade per [the release notes](https://github.com/cosmos/gaia/releases/tag/v8.0.0). Did you just swap out the binaries?

**Comment by lcgogo** [comment]
> Hi @lcgogo, are you trying to join in mainnet ? mainnet is not on v8 yet. [Rho-testnet is using v8](https://github.com/cosmos/testnets/tree/master/public)

Yes, want to use 8.0.0 in mainnet because I see https://github.com/cosmos/gaia/releases/tag/v8.0.0
and think Rho is a new hardfork short name.

When will the 8.0.0 apply in mainnet?

**Comment by mmulji-ic** [comment]
The upgrade is proposed to take place at height 14,099,412 which should occur approximately at +/- February 16th 2023 at approximately 13:00 UTC.

In the meantime, if you want to use mainnet, try with [version 7.1.1](https://github.com/cosmos/gaia/releases/tag/v7.1.1)

**Comment by fmira21** [comment]
Hi guys!
I have the same error, but with the version 7.1.1:

```
12:53PM INF service start impl=MConn{34.141.15.99:26656} module=p2p msg={} peer={"id":"ba3bacc714817218562f743178228f23678b2873","ip":"34.141.15.99","port":26656}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1598dad]
goroutine 43 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc001049440, 0xb}, 0xc009b22810, {0x27472b8, 0xc009b63760}, {0x2767650, 0xc000596520}, 0xc009b7c0f0, {0x2740f20, 0xc000177180}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/upgrade/abci.go:38 +0x100d
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x275b548, 0xc000056030}, {0x2767208, 0xc004fecd00}, {{0xb, 0x0}, {0xc011132030, 0xb}, 0xd596e2, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/types/module/module.go:491 +0x3bb
github.com/cosmos/gaia/v9/app.(*GaiaApp).BeginBlocker(_, {{0x275b548, 0xc000056030}, {0x2767208, 0xc004fecd00}, {{0xb, 0x0}, {0xc011132030, 0xb}, 0xd596e2, ...}, ...}, ...)
	github.com/cosmos/gaia/v9/app/app.go:245 +0x85
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc004fb20e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc011132030, 0xb}, 0xd596e2, {0x121cb77c, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.12/baseapp/abci.go:177 +0x97c
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc004fb20e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc011132030, 0xb}, 0xd596e2, {0x121cb77c, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc004fb20e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc011132030, 0xb}, 0xd596e2, {0x121cb77c, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x275c380?, 0xc000dffaa0}, {0x2761e00, 0xc000f2af90}, 0xc002c2e1e0, {0x2768b98, 0xc018640150}, 0xd596e1?)
	github.com/tendermint/tendermint@v0.34.24/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0a995cba0, 0x8}}, {0xc0a995cbb0, 0xb}, 0x4f5b97, 0xd596e1, {{0xc008895800, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.24/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000177c00, 0x0)
	github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:112 +0x7a
```

Is mainnet not on 7.1.1 as well?

**Comment by yaruwangway** [comment]
mainnet is using v7.1.1,  can you tell us more about your setup steps to sync the mainnet ?

**Comment by mmulji-ic** [comment]
Hi @lcgogo pinging to see if this is still an active issue, if not we will close in a weeks time.

**Comment by mmulji-ic** [comment]
Hi @lcgogo closing because we didn't hear back from you. Please reopen if the issue persists.
