### ISSUE TITLE
panic when upgrade to v11.0.0

### ISSUE THREAD

**Issue by nuaays** [cosmos/gaia#2685]
## Summary of Bug
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17ebbd4]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc000f64900, 0xb}, 0xc0014049f0, {0x2655ac0, 0xc0014346f0}, {0x2678070, 0xc000f7a1c0}, 0xc0014055f0, {0x264f6a0, 0xc000190e00}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/x/upgrade/abci.go:38 +0x1014
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x266a0e8, 0xc000068030}, {0x2677cb0, 0xc04c7be180}, {{0xb, 0x0}, {0xc04c5db0a0, 0xb}, 0xfa9a97, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/types/module/module.go:491 +0x1db
github.com/cosmos/gaia/v11/app.(*GaiaApp).BeginBlocker(...)
	github.com/cosmos/gaia/v11/app/app.go:235
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc04c7b14c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc04c5db0a0, 0xb}, 0xfa9a97, {0x2983df5f, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/baseapp/abci.go:177 +0x97b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc04c7b14c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc04c5db0a0, 0xb}, 0xfa9a97, {0x2983df5f, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc04c7b14c0, 0x20, 0x20}, {{0xb, 0x0}, {0xc04c5db0a0, 0xb}, 0xfa9a97, {0x2983df5f, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x266aee8?, 0xc000c12720}, {0x2672040, 0xc0011ca6e0}, 0xc0001db680, {0x26796a8, 0xc000f7c210}, 0xfa9a96?)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:307 +0x51d
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0011c9ee0, 0x7}}, {0xc0011c9ef0, 0xb}, 0x4f5b97, 0xfa9a96, {{0xc001865220, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0011c9ee0, 0x7}}, {0xc0011c9ef0, 0xb}, 0x4f5b97, 0xfa9a96, {{0xc001865220, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0011c9ee0, 0x7}}, {0xc0011c9ef0, 0xb}, 0x4f5b97, 0xfa9a96, {{0xc001865220, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc04c7cdc78, {0x267abf0, 0xc0001d8000})
	github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0011c9ee0, 0x7}}, {0xc0011c9ef0, 0xb}, 0x4f5b97, 0xfa9a96, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00020e3c0, {0x2666dd0, 0xc00106d400}, 0xc0001339e0, {0x2650a80, 0xc000dc8d98}, 0x0?, 0x61a80?, 0xc000133c20, {0x266aee8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/node/node.go:779 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2687568, 0xc000204db0}, {0x0, 0x0}, {0x266f2d8, 0xc000f7a1c0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/server/start.go:280 +0x89b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000fa6f00?, {0xc001052480?, 0x0?, 0x4?})
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000fa6f00, {0xc001052440, 0x4, 0x4})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d17200)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000f64900, 0xb})
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/cosmos/gaia/v11/cmd/gaiad/main.go:16 +0x2c
```

## Version
v11.0.0

## Steps to Reproduce

upgrade gaiad from v10.0.2 to v11.0.0
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by mpoke** [comment]
@nuaays Please note that upgrading to v11.0.0 requires a coordinated network upgrade. Currently, the proposal to upgrade to v11.0.0 is in the voting period https://www.mintscan.io/cosmos/proposals/804.

**Comment by mpoke** [comment]
@nuaays If you need further information, please reopen.
