### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by djacksch** [cosmos/gaia#2689]
## Summary of Bug

Upgrading from v10.0.1 -> v10.0.2
One sentry node upgraded without issue. 2nd sentry node gives this error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15e8ad4]

goroutine 179 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7fffdd9f48eb, 0x5}, 0xc001c8c780, {0x2671ce0, 0xc001d12310}, {0x2694390, 0xc0011b4200}, 0xc001d1a240, {0x266b860, 0xc000614c40}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/x/upgrade/abci.go:38 +0x1014
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2686368, 0xc000060028}, {0x2693fd0, 0xc001dc1100}, {{0xb, 0x0}, {0xc0044aa120, 0xb}, 0xfb843b, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/types/module/module.go:491 +0x1db
github.com/cosmos/gaia/v11/app.(*GaiaApp).BeginBlocker(...)
	github.com/cosmos/gaia/v11/app/app.go:233
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0066d55e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0044aa120, 0xb}, 0xfb843b, {0x88f30ea, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.16-ics/baseapp/abci.go:177 +0x97b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0066d55e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0044aa120, 0xb}, 0xfb843b, {0x88f30ea, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0066d55e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc0044aa120, 0xb}, 0xfb843b, {0x88f30ea, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x26871a0?, 0xc00774a180}, {0x268e300, 0xc007c78c80}, 0xc00067a3c0, {0x26959c8, 0xc00e944930}, 0xfb843a?)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:307 +0x51d
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc00149a0f0, 0x7}}, {0xc00149a100, 0xb}, 0x4f5b97, 0xfb843a, {{0xc000ec3180, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.27/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000615500, 0x0)
	github.com/tendermint/tendermint@v0.34.27/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.27/blockchain/v0/reactor.go:112 +0x7a

## Version

 v10.0.2 
 a2b14cd 

## Steps to Reproduce
 Install version v10.0.2
run gaiad init
download snapshot
Restart gaiad

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by djacksch** [comment]
If I revert to version v10.0.1 it starts syncing with no errors.

**Comment by yaruwangway** [comment]
hi, can you give us more infos ? how you sync with v10.0.1 and how you switch to v1.0.2 ?

**Comment by djacksch** [comment]
I just started from scratch to re-test. 
1) delete datadir - data & config
2) gaiad init --chain-id cosmoshub-4
3) download genesis https://snapshots.polkachu.com/genesis/cosmos/genesis.json
4) download addrbook https://snapshots.polkachu.com/addrbook/cosmos/addrbook.json
5) download snapshot https://snapshots.polkachu.com/snapshots/cosmos/cosmos_16479361.tar.lz4
6) gaiad start (using same flags we have been using since version 9)

**Comment by djacksch** [comment]
I get the above error.

If I now revert back to v10.0.1 it runs and starts syncing. I have no idea what I'm doing wrong.

**Comment by djacksch** [comment]
I am also building from source if that makes a difference

git clone --recursive https://www.github.com/cosmos/gaia
git checkout $ATOM_VERSION
make install

**Comment by djacksch** [comment]
UPDATE! I used the release binary download and I am having no issues.

**Comment by yaruwangway** [comment]
Hi, just confirm what you meant:
genesis: https://snapshots.polkachu.com/genesis/cosmos/genesis.json
1. if you run v10.0.1 with this genesis, working
2. if you run v10.0.1 with this genesis for a while,  then switch to v10.0.2 (build from git repo), not working
3.  if you run v10.0.1 with this genesis for a while,  then switch to v10.0.2 (released binary) , working 
4. if you run v10.0.2 directly with the genesis, not working  ?

Is this correct ?

**Comment by djacksch** [comment]
4. if you run v10.0.2 directly with the genesis, not working (build from git repo)
5. if you run v10.0.2 directly  with the genesis  (released binary) , working
Yes 100% correct!

**Comment by yaruwangway** [comment]
4. if you run v10.0.2 directly with the genesis, not working, you see panic ?
i tested, no panics. do you use state sync ?

**Comment by yaruwangway** [comment]
please make sure when you build from source code, the version is v10.0.2, you can check the version by `gaiad version` if you build by `make install`

**Comment by mpoke** [comment]
Closing issue due to lack of activity. @djacksch Please let us know if the problem persists.
