### ISSUE TITLE
[Bug]: error when parsing blocks produced around v15 upgrade

### ISSUE THREAD

**Issue by kevink1103** [cosmos/gaia#3016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When trying to parse blocks produced around v15 upgrade (ranging from 19639579~19639607), the following error occurs:

```
codespace sdk code 2: tx parse error: no concrete type registered for type URL /cosmos.authz.v1beta1.MsgRevoke against interface *tx.TxExtensionOptionI
```

### Cosmos SDK Version

v0.47.10-ics-lsm

### How to reproduce?

```go
import (
	"cosmossdk.io/x/authz"
	"fmt"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/tx"

	// ...
)

// ...

a := &types.Any{
	TypeUrl: "/cosmos.authz.v1beta1.MsgRevoke",
	// Value:   b, anything you'd like to put here
}
fmt.Println(a.TypeUrl)
var txExtensionOptionI tx.TxExtensionOptionI
err = registry.UnpackAny(a, &txExtensionOptionI)
fmt.Println(err.Error())
```

use the above code inside this test code:

https://github.com/cosmos/cosmos-sdk/blob/27a231ae4816fd8c3ee39a1cc02eccf977fb1b79/codec/types/types_test.go#L15

**Comment by xihucuyu888** [comment]
same error
sample：
/cosmos/tx/v1beta1/txs/FC4F5CC29C6DB6566FAD7FC42726AF3D7EB0BAAC678F871065C11FD89E1EE5D0

**Comment by julienrbrt** [comment]
I believe asteroid protocol mentioned that: https://x.com/asteroidxyz/status/1770289081752097232?s=46.

This seems more a hub related question than a sdk btw.

**Comment by kevink1103** [comment]
@julienrbrt the X post mentions `After Block 19639600 (linked below), transactions that use the legacy format will be invalid.`.
The error occurs when parsing blocks that's even before the stated block number :(

**Comment by Unded** [comment]
I've got the same error when processing **19625062** block:
```
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: codespace sdk code 2: tx parse error: no concrete type registered for type URL /cosmos.authz.v1beta1.MsgRevoke against interface *tx.TxExtensionOptionI
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at cosmos.tx.v1beta1.ServiceGrpc$ServiceBlockingStub.getTxsEvent(ServiceGrpc.java:690)
        ...
```

**Comment by MSalopek** [comment]
Replicated:
```shell
gaiad q tx FC4F5CC29C6DB6566FAD7FC42726AF3D7EB0BAAC678F871065C11FD89E1EE5D0 --node [https://cosmos-rpc.polkachu.com:443](https://cosmos-rpc.polkachu.com/)
Error: no concrete type registered for type URL /cosmos.authz.v1beta1.MsgRevoke against interface *tx.TxExtensionOptionI: tx parse error
Usage:
```

Some there are Txs on mainnet that misappropriated `MsgRevoke` to store some data back on cosmos-sdk v0.45.
* cosmos-sdk/v0.45 did not have checks for `non_critical_extension_options` field.
* cosmos-sdk/v0.47 has checks for `non_critical_extension_options` -> does not touch content but attempts to unmarshal

Tx:
```js
{
  "header": {
    "chain_id": "cosmoshub-4",
    "timestamp": "2024-03-20T10:15:33Z"
  },
  "data": {
    "height": "19639358",
    "txhash": "FC4F5CC29C6DB6566FAD7FC42726AF3D7EB0BAAC678F871065C11FD89E1EE5D0",
    ...
    "tx": {
      "@type": "/cosmos.tx.v1beta1.Tx",
      "body": {
        "messages": [
          {
            "@type": "/cosmos.bank.v1beta1.MsgSend",
            "from_address": "cosmos10y85trfe9axzlpu3350cpjscxzvtpqjkkjcx4c",
            "to_address": "cosmos10y85trfe9axzlpu3350cpjscxzvtpqjkkjcx4c",
            "amount": [
              {
                "denom": "uatom",
                "amount": "1"
              }
            ]
          }
        ],
        "memo": "urn:inscription:cosmoshub-4@v1;inscribe$h=1e16d10018b03f227d96abb3774b83586ac98dc4979fa3f23bb3f0404ae98661",
        "timeout_height": "0",
        "extension_options": [],
        "non_critical_extension_options": [ 
          // this is the issue
          {
            "@type": "/cosmos.authz.v1beta1.MsgRevoke",
            "granter": ...,
            "grantee": ...,
            "msg_type_url": "urn:inscription:cosmoshub-4@v1;inscribe$h=1e16d10018b03f227d96abb3774b83586ac98dc4979fa3f23bb3f0404ae98661"
          }
        ]
      }
      ...
    },
    "timestamp": "2024-03-20T10:15:33Z",
    "events": []
  }
}
```

**Comment by MSalopek** [comment]
Fixed by: https://github.com/cosmos/gaia/pull/3035
