### ISSUE TITLE
cosmos mainnet 19.1.0 node suddenly crashes with error [panic: version does not exist]

### ISSUE THREAD

**Issue by jay-ginco** [cosmos/gaia#3291]
Hi team, my node has been running fine after 19.1.0 version upgrade and hardfork, however, it suddenly starts crashing with below logs:

```
 INF fee deduct post handle gas consumed=964995 min gas prices=0.005000000000000000uatom module=server5:13PM INF fee deduct post handle fee=4838uatom module=server tip=3894uatom5:13PM 
INF updated the fee market module=x/feemarket params={"alpha":"0.000000000000000000","beta":"1.000000000000000000","delta":"0.000000000000000000","enabled":true,"fee_denom":"uatom","gamma":"0.000000000000000000","max_block_utilization":30000000,"max_learning_rate":"0.125000000000000000","min_base_gas_price":"0.005000000000000000","min_learning_rate":"0.125000000000000000","window":1}5:13PM INF updated the fee market average_block_utilization=0.032166500000000000 height=21850218 module=x/feemarket net_block_utilization=-14035005 new_base_gas_price=0.005000000000000000 new_learning_rate=0.1250000000000000005:13PM 
INF finalized block block_app_hash=1D4E6ABFA42A22145145E4BED7BBA06F9AC0CE9B747D35078D51B1C5A8EED50F height=21850218 module=consensus num_txs_res=1 num_val_updates=05:13PM INF executed block app_hash=1D4E6ABFA42A22145145E4BED7BBA06F9AC0CE9B747D35078D51B1C5A8EED50F height=21850218 module=consensus5:13PM 
INF Closing application.db module=server5:13PM 
INF Closing snapshots/metadata.db module=server
panic: version does not exist
```

I have tried restarting the node, but no improvements, kindly suggest

**Comment by MSalopek** [comment]
Thanks for opening the issue!

Could you provide some more context?
* what are your pruning settings?
* are you creating snapshots?
* was the node synced from an existing snapshot or using statesync?
* do you have a `wasm` directory in your node home?
* can the node continue, or does it alway stay at `21850218`?

**Comment by jay-ginco** [comment]
Sure:

- prunning settings:
pruning = "default"

- are you creating snapshots? How do I know this, I do see snapshots dir present

- I used polkachu snapshot to recover my nodes
https://polkachu.com/tendermint_snapshots/cosmos

- wasm folder I am using from polkachu snapshot itself

- No, it stops at that height and crashes, I have two nodes, both started to sync after recovering from snapshot, howere after 5 hours, one node crashed with above error, and now I see node 2 is also crashing with same error after a day of running fine with below logs:

```
10:01AM INF finalized block block_app_hash=F53C7966AEE5284E4ACCA224E900E4A35D6F91BB7AE6359A93621A90C18249CE height=21859240 module=consensus num_txs_res=6 num_val_updates=0
10:01AM INF executed block app_hash=F53C7966AEE5284E4ACCA224E900E4A35D6F91BB7AE6359A93621A90C18249CE height=21859240 module=consensus
10:01AM INF Closing application.db module=server
10:01AM INF Closing snapshots/metadata.db module=server
panic: version does not exist

goroutine 1 [running]:
cosmossdk.io/store/iavl.(*Store).Commit(0xc00437dd40?)
	cosmossdk.io/store@v1.1.0/iavl/store.go:128 +0xd7
cosmossdk.io/store/rootmulti.commitStores(0x14d8ba8, 0xc00356a210, 0xc001ccd680)
	cosmossdk.io/store@v1.1.0/rootmulti/store.go:1196 +0x158
cosmossdk.io/store/rootmulti.(*Store).Commit(0xc001a56800)
	cosmossdk.io/store@v1.1.0/rootmulti/store.go:482 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00079ad88)
	github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/abci.go:930 +0x2e2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/cmt_abci.go:56
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x20?, {0x4f8aba8?, 0x72c0880?}, 0xc026743600?)
	github.com/cometbft/cometbft@v0.38.11/abci/client/local_client.go:113 +0xcd
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc0015198d8, {0x4f8aba8, 0x72c0880})
	github.com/cometbft/cometbft@v0.38.11/proxy/app_conn.go:109 +0x168
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba8, {{0xc00150dd00, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/state/execution.go:404 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba8, {{0xc00150dd00, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/state/execution.go:290 +0xf10
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba7, {{0xc001200b40, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/state/execution.go:219 +0x1d9
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba7, {{0xc001200b40, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/consensus/replay.go:534 +0x24e
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/consensus/replay.go:433 +0x77a
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc026745190, {0x4f8ab00, 0xc001759db0}, {0x4fad158, 0xc000db28c0})
	github.com/cometbft/cometbft@v0.38.11/consensus/replay.go:274 +0x425
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/node/setup.go:186 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x4f8ab00, 0xc001759db0}, 0xc002503a40, {0x4f64aa0, 0xc001b6e1e0}, 0xc003e1a1c0, {0x4f4b6e0, 0xc0016ac570}, 0xc0018e8280, 0x4852d28, ...)
	github.com/cometbft/cometbft@v0.38.11/node/node.go:360 +0x630
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x4f8ab00, 0xc001759db0}, 0xc002503a40, {0x4fd5b50, 0xc000aa6a08}, 0xc001aa0e80)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:377 +0x42f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0xc002516ff0, 0xb}, 0x0, {0xc0025175e0, 0x7}, {0x40811c8, 0x1}, {0x40811c8, 0x1}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:323 +0x17c
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x4fb1858, 0xc00213aa80}, 0x0, {0xc001e11520, 0xb}, {0x4fd5a88, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:240 +0x2c7
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:198 +0x63
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc001aa0e80, 0xc002377a20)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:570 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc001274308, {0xc001aa1020?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:197 +0x212
github.com/spf13/cobra.(*Command).execute(0xc001274308, {0xc001aa1000, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e8af08)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e8af08, {0x0, 0x0}, {0xc000f95310, 0xb})
	github.com/cosmos/cosmos-sdk@v0.50.9/server/cmd/execute.go:34 +0x187
main.main()
	github.com/cosmos/gaia/v19/cmd/gaiad/main.go:15 +0x2a
```

**Comment by MSalopek** [comment]
Judging by what's going in on discords, the issue could be with the `wamd` directory.

Please use a newer snapshot and take note to include the `wasm` directory if you are using a script to bootstrap a node. This has been happening for a couple days now - seems to be related to your issue.

Please let me know if this happens again. I can see polkachu has added instructions for `wasmd` and some checks.

If that does not work, try different snapshots:
* https://www.imperator.co/services/chain-services/mainnets/cosmos

**Comment by jay-ginco** [comment]
Still seems to be issue, it runs fine for few hours syncing to latest block, than starts crashing with:

```
4:16AM INF finalized block block_app_hash=0AEB730E8D377840AB9D905832C4CAF7CEBAC7AA971ABDE010D8E5696F3EA81E height=21868467 module=consensus num_txs_res=1 num_val_updates=04:16AM INF executed block app_hash=0AEB730E8D377840AB9D905832C4CAF7CEBAC7AA971ABDE010D8E5696F3EA81E height=21868467 module=consensus4:16AM INF Closing application.db module=server4:16AM INF Closing snapshots/metadata.db module=server
panic: version does not exist

goroutine 1 [running]:
cosmossdk.io/store/iavl.(*Store).Commit(0xc00437dd40?)
	cosmossdk.io/store@v1.1.0/iavl/store.go:128 +0xd7
cosmossdk.io/store/rootmulti.commitStores(0x14d8ba8, 0xc00356a210, 0xc001ccd680)
	cosmossdk.io/store@v1.1.0/rootmulti/store.go:1196 +0x158
cosmossdk.io/store/rootmulti.(*Store).Commit(0xc001a56800)
	cosmossdk.io/store@v1.1.0/rootmulti/store.go:482 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc00079ad88)
	github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/abci.go:930 +0x2e2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Commit(...)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/cmt_abci.go:56
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x20?, {0x4f8aba8?, 0x72c0880?}, 0xc026743600?)
	github.com/cometbft/cometbft@v0.38.11/abci/client/local_client.go:113 +0xcd
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc0015198d8, {0x4f8aba8, 0x72c0880})
	github.com/cometbft/cometbft@v0.38.11/proxy/app_conn.go:109 +0x168
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba8, {{0xc00150dd00, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/state/execution.go:404 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba8, {{0xc00150dd00, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/state/execution.go:290 +0xf10
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba7, {{0xc001200b40, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/state/execution.go:219 +0x1d9
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, 0x14d8ba7, {{0xc001200b40, ...}, ...}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/consensus/replay.go:534 +0x24e
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, 0x4f5b97, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/consensus/replay.go:433 +0x77a
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc026745190, {0x4f8ab00, 0xc001759db0}, {0x4fad158, 0xc000db28c0})
	github.com/cometbft/cometbft@v0.38.11/consensus/replay.go:274 +0x425
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0xc0020bb118, 0x6}}, {0xc0020bb150, 0xb}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.11/node/setup.go:186 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x4f8ab00, 0xc001759db0}, 0xc002503a40, {0x4f64aa0, 0xc001b6e1e0}, 0xc003e1a1c0, {0x4f4b6e0, 0xc0016ac570}, 0xc0018e8280, 0x4852d28, ...)
	github.com/cometbft/cometbft@v0.38.11/node/node.go:360 +0x630
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x4f8ab00, 0xc001759db0}, 0xc002503a40, {0x4fd5b50, 0xc000aa6a08}, 0xc001aa0e80)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:377 +0x42f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0xc002516ff0, 0xb}, 0x0, {0xc0025175e0, 0x7}, {0x40811c8, 0x1}, {0x40811c8, 0x1}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:323 +0x17c
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x4fb1858, 0xc00213aa80}, 0x0, {0xc001e11520, 0xb}, {0x4fd5a88, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:240 +0x2c7
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:198 +0x63
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc001aa0e80, 0xc002377a20)
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:570 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc001274308, {0xc001aa1020?, 0x0?, 0x2?})
	github.com/cosmos/cosmos-sdk@v0.50.9/server/start.go:197 +0x212
github.com/spf13/cobra.(*Command).execute(0xc001274308, {0xc001aa1000, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e8af08)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e8af08, {0x0, 0x0}, {0xc000f95310, 0xb})
	github.com/cosmos/cosmos-sdk@v0.50.9/server/cmd/execute.go:34 +0x187
main.main()
	github.com/cosmos/gaia/v19/cmd/gaiad/main.go:15 +0x2a
@MSalopek

```

**Comment by MSalopek** [comment]
> Still seems to be issue, it runs fine for few hours syncing to latest block, than starts crashing with:
> 
> ```
> 4:16AM INF finalized block block_app_hash=0AEB730E8D377840AB9D905832C4CAF7CEBAC7AA971ABDE010D8E5696F3EA81E height=21868467 module=consensus num_txs_res=1 num_val_updates=04:16AM INF executed block app_hash=0AEB730E8D377840AB9D905832C4CAF7CEBAC7AA971ABDE010D8E5696F3EA81E height=21868467 module=consensus4:16AM INF Closing application.db module=server4:16AM INF Closing snapshots/metadata.db module=server
> panic: version does not exist

Unfortunately, the error log is not giving me any useful information.

How are you getting the binary? Are you simply downloading it or are you building it yourself?

Maybe try `make install` if you are downloading the binary, or download it if you are running `make install`.

Additionally, could you post the script that bootstraps your node?

**Comment by jay-ginco** [comment]
Thanks, looks like it was snpashot issue, node with newer snapshot is running fine since 2 days

**Comment by MSalopek** [comment]
Closing as no further action is necessary.
