### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by JohnsonCaii** [cosmos/gaia#415]
## Summary of Bug
```
I[2020-05-30|00:03:09.207] Executed block                               module=state height=862478 validTxs=0 invalidTxs=0
I[2020-05-30|00:03:09.245] Committed state                              module=state height=862478 txs=0 appHash=15E8EA70F91236E4E45D0710D0D17D096695A8821EDAEE188E9EFEDA912C78E8
panic: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0xa7b2020 got=0x602df708 [file=133182.ldb]

goroutine 85 [running]:
github.com/tendermint/tm-db.(*GoLevelDB).SetSync(0xc0000ac150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/go_level_db.go:77 +0xfc
github.com/tendermint/tendermint/store.(*BlockStore).SaveBlock(0xc000e58e40, 0xc00e763680, 0xc00d258a00, 0xc00e5b0f00)
        /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/store/store.go:187 +0x566
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00021a1a0)
        /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/blockchain/v0/reactor.go:336 +0x8df
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/.go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/blockchain/v0/reactor.go:118 +0x84
```
I got the above error and cannot continue unless removing all the data and resync. It's a drop-dead halt.

## Version
v2.0.9

I've also tried v2.0.10, that shows me another error(**on table-footer (pos=2112911): bad magic number**).

## Steps to Reproduce
seeds in config.toml
```
seeds = "ba3bacc714817218562f743178228f23678b2873@5.83.160.108:26656,1e63e84945837b026f596ed8ae68708783d04ad4@51.75.145.123:26656,d2d452e7c9c43fa5ef017552688de60a5c0053ee@34.245.217.163:26656,dd36969b56c740bb40bb8badd4d4c6facc35dc24@206.189.115.41:26656,a0aca8fb801c69653a290bd44872e8457f8b0982@47.99.180.54:26656,27f8dd3bdbecbef7192291083706c156e523d8e0@3.122.248.21:26656,aee0df1a660f301d456a0c2f805b372f7341e8ec@63.35.230.143:26656,7d1f660b361d6286715c098a3a171e554e9642bb@34.254.205.37:26656,fa105c2291ac4aa452552fa4835266300a8209e1@88.198.41.62:26656,bd410d4564f7e0dd9a0eb16a64c337a059e11b80@47.103.35.130:26656"
```

____

**Comment by alexanderbez** [comment]
Looks like you're DB is corrupted. Unfortunately, there isn't much we can do here. You'll have to restore to a snapshot and/or backup. Maybe try posting this in the TM repo and see if others have seen this?

**Comment by JohnsonCaii** [comment]
So you are saying that I should backup db data each a while like 500,000 blocks?

**Comment by alexanderbez** [comment]
You should be doing periodic backups, absolutely, yes.

**Comment by JohnsonCaii** [comment]
Ok thanks. I'll have a try.
