### ISSUE TITLE
Panic on gaia v3 with -x-crisis-invariants

### ISSUE THREAD

**Issue by zmanian** [cosmos/gaia#489]
Debugging a panic that manifests with `-x-crisis-invariants` on migrated hub genesis

This is on the `jack/gaiav3.0` branch.

`gaia/build/gaiad --home /Users/zakimanian/cosmoshub-test-stargate start --x-crisis-skip-assert-invariants`

Oddly `gaia/build/gaiad --home /Users/zakimanian/cosmoshub-test-stargate start`

Appears to get past InitGenesis which doesn't make a whole lot of sense.

```
panic: json: cannot unmarshal string into Go value of type map[string]*json.RawMessage

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc00025e2d0, 0xc00abdc000, 0x7dd44a, 0x7de000, 0x5b6e880, 0xc0006ce000)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc2/codec/proto_codec.go:159 +0x8a
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis(0x5b94660, 0xc00025e2d0, 0x5b5df00, 0xc0005a2b20, 0x5b8e320, 0xc00025e2d0, 0x5b80900, 0xc0000c8870, 0x6f38258, 0xc0005b4c60, ...)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc2/x/staking/module.go:148 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc0005a4d90, 0x5b7c940, 0xc000046088, 0x5b91ce0, 0xc00001c480, 0x0, 0x0, 0xc000120110, 0xb, 0x364924, ...)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc2/types/module/module.go:304 +0x2b5
github.com/cosmos/gaia/app.(*GaiaApp).InitChainer(0xc0001fa300, 0x5b7c940, 0xc000046088, 0x5b91ce0, 0xc00001c480, 0x0, 0x0, 0xc000120110, 0xb, 0x364924, ...)
	github.com/cosmos/gaia/app/app.go:452 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0000b31e0, 0x0, 0xed5830c36, 0x0, 0xc000120110, 0xb, 0xc00000fe40, 0xc000fb8c00, 0x7d, 0x7d, ...)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc2/baseapp/abci.go:62 +0x318
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00104e540, 0x0, 0xed5830c36, 0x0, 0xc000120110, 0xb, 0xc00000fe40, 0xc000fb8c00, 0x7d, 0x7d, ...)
	github.com/tendermint/tendermint@v0.34.0-rc5/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc001210140, 0x0, 0xed5830c36, 0x0, 0xc000120110, 0xb, 0xc00000fe40, 0xc000fb8c00, 0x7d, 0x7d, ...)
	github.com/tendermint/tendermint@v0.34.0-rc5/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc01d3de748, 0xb, 0x0, 0xc0006bc010, 0x6, 0xc0006bc020, 0xb, 0x364924, 0x0, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.0-rc5/consensus/replay.go:319 +0x695
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01d3de748, 0x5b95c20, 0xc0001a80d0, 0xc00130d6b0, 0x203000)
	github.com/tendermint/tendermint@v0.34.0-rc5/consensus/replay.go:268 +0x4d8
github.com/tendermint/tendermint/node.doHandshake(0x5b91f60, 0xc00063e630, 0xb, 0x0, 0xc0006bc010, 0x6, 0xc0006bc020, 0xb, 0x364924, 0x0, ...)
	github.com/tendermint/tendermint@v0.34.0-rc5/node/node.go:277 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0010a8640, 0x5b73bc0, 0xc0006463c0, 0xc0005a3ea0, 0x5b410a0, 0xc0006676e0, 0xc0005a3f10, 0x598d9e0, 0xc00063e000, 0x5b7cf00, ...)
	github.com/tendermint/tendermint@v0.34.0-rc5/node/node.go:685 +0x1da5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0010c7400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5b7cb00, 0xc00108e2d0, ...)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc2/server/start.go:235 +0x5d7
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0010bdb80, 0xc0011a8660, 0x0, 0x3, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc2/server/start.go:117 +0x154
github.com/spf13/cobra.(*Command).execute(0xc0010bdb80, 0xc0010eb0c0, 0x3, 0x4, 0xc0010bdb80, 0xc0010eb0c0)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f6c840, 0x0, 0x0, 0xc001063280)
```
 Reproduce with https://storage.googleapis.com/stargate-genesis/genesis.sorted.json

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zmanian** [comment]
Never mind it's happening on with or without the flag.

**Comment by zmanian** [comment]
Looks like a false positive!
