### ISSUE TITLE
gaia start error

### ISSUE THREAD

**Issue by zramsay** [cosmos/gaia#50]
```
panic: Panicked questionably: Failed to process committed block (284:34433944323933433138394445363935394343434244383631384236374231323544393941374539): Exec failed for application: Wrong Block.Header.AppHash.  Expected 64B8F8DA7DB59DA194A1EC42ED3089885F52C2B7, got 17015D1E5E2A8FF763E559F218F7AF57D77BD155

goroutine 55 [running]:
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/common.PanicQ(0xb1e600, 0xc422eaf490)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/common/errors.go:44 +0xdd
github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc4200a1cc0)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:277 +0x1014
created by github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:97 +0x8a
```

**Comment by zramsay** [comment]
```
 gaiacli tx bond --amount=10fermion --name=zach --pubkey=84E70F97CB8649541BB9699B6E573132A5DF28C44C105BBC899673715515C073
Please enter passphrase for zach: 
panic: Panicked on a Sanity Check: Unexpected struct type stake.BondUpdate for registered interface TxInner. Was it registered as a pointer receiver rather than as a value receiver?

goroutine 1 [running]:
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0xb13720, 0xc4203205c0)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/common/errors.go:26 +0xdd
github.com/cosmos/gaia/vendor/github.com/tendermint/go-wire.BinaryBytes(0xbac200, 0xc420320430, 0xc420320430, 0xc420310fc0, 0xc420320430)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/go-wire/util.go:17 +0xb6
github.com/cosmos/gaia/vendor/github.com/tendermint/go-wire/data.ToWire(0xbac200, 0xc420320430, 0xbac200, 0xc420320430, 0x20, 0x12ea040, 0xc4203189c0)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/go-wire/data/binary.go:31 +0x35
github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/modules/auth.(*OneSig).SignBytes(0xc420310fc0, 0x1345340, 0x12e7720, 0xc4202b0d30)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/modules/auth/tx.go:92 +0x55
github.com/cosmos/gaia/vendor/github.com/tendermint/go-crypto/keys/cryptostore.Manager.Sign(0x12e39e0, 0x1345340, 0x12e7720, 0xc4202b0d30, 0x12e1960, 0xc4202a71d0, 0x7ffe77756ebd, 0x4, 0xc4203202f0, 0xa, ...)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/go-crypto/keys/cryptostore/holder.go:111 +0x104
github.com/cosmos/gaia/vendor/github.com/tendermint/go-crypto/keys/cryptostore.(*Manager).Sign(0xc4202a7230, 0x7ffe77756ebd, 0x4, 0xc4203202f0, 0xa, 0x7f5617dab818, 0xc420310fc0, 0xc420101a08, 0x40f31d)
	<autogenerated>:19 +0xb4
github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/client/commands/txs.signTx(0x12ea100, 0xc4202a7230, 0x7f5617dab818, 0xc420310fc0, 0x7ffe77756ebd, 0x4, 0x5, 0x5)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/client/commands/txs/helpers.go:184 +0x150
github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/client/commands/txs.SignTx(0x12e1560, 0xc420310fc0, 0xc4202a7110, 0x12e1560)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/client/commands/txs/helpers.go:108 +0x157
github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/client/commands/txs.DoTx(0x12e1560, 0xc420310fc0, 0xa, 0x12ea040)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/cosmos/cosmos-sdk/client/commands/txs/helpers.go:70 +0x82
github.com/cosmos/gaia/modules/stake/commands.cmdBondUpdate(0x12ceaa0, 0xc4202a6d20, 0x0, 0x3, 0xd4b0b0, 0x0, 0x0)
	/home/zicter/goApps/src/github.com/cosmos/gaia/modules/stake/commands/tx.go:83 +0x106
github.com/cosmos/gaia/modules/stake/commands.cmdBond(0x12ceaa0, 0xc4202a6d20, 0x0, 0x3, 0x0, 0x0)
	/home/zicter/goApps/src/github.com/cosmos/gaia/modules/stake/commands/tx.go:64 +0x55
github.com/cosmos/gaia/vendor/github.com/spf13/cobra.(*Command).execute(0x12ceaa0, 0xc4202a6c60, 0x3, 0x3, 0x12ceaa0, 0xc4202a6c60)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/spf13/cobra/command.go:698 +0x47b
github.com/cosmos/gaia/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x12d4c60, 0x24, 0xc4202b02ca, 0xc4202b0330)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/cosmos/gaia/vendor/github.com/spf13/cobra.(*Command).Execute(0x12d4c60, 0xc42024dde0, 0xc42024dde0)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x12d4c60, 0xd4c750, 0x2, 0xc42024dd60)
	/home/zicter/goApps/src/github.com/cosmos/gaia/vendor/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/home/zicter/goApps/src/github.com/cosmos/gaia/cmd/gaiacli/main.go:95 +0x4f9
```

**Comment by rigelrozanski** [comment]
Is this on `feature/delegation`?

**Comment by adrianbrink** [comment]
@zramsay

**Comment by rigelrozanski** [comment]
should be resolved hmu if not

**Comment by ValarDragon** [comment]
I think in the time period when we are trying to find bugs in the SDK / when the next state breaking bug is found, I think it would definitely be worth the time for someone to test out either the delve tool or gofail tool. I do think this is something worth doing prelaunch, as #postlaunch when the network fails we want to optimize for our time to recovery. (And the more tooling we can use, the easier that becomes)

**Comment by cwgoes** [comment]
Yes, we don't have bisection yet, also see https://github.com/cosmos/cosmos-sdk/pull/1938 and https://github.com/cosmos/cosmos-sdk/pull/2106 (I'm not sure what the status of those are).
