### ISSUE TITLE
Panic on gaia v3.0.0 after upgrading from v2.0.14

### ISSUE THREAD

**Issue by gituser** [cosmos/gaia#531]
## Summary of Bug

gaiad raise panic error instead of starting after upgrading gaiad from `v2.0.14` to `v3.0.0`:

```
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #033[90m1:09AM#033[0m #033[32mINF#033[0m starting ABCI with Tendermint
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: panic: proto: Int64Value: wiretype end group for non-group
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: goroutine 1 [running]:
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/store/rootmulti.getLatestVersion(0x20761c0, 0xc000010150, 0x205ef40)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/store/rootmulti/store.go:908 +0x10b
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).LoadLatestVersion(0xc000e14280, 0xc0004e8000, 0x7f9f07754108)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/store/rootmulti/store.go:158 +0x37
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/baseapp.DefaultStoreLoader(0x207d800, 0xc000e14280, 0xc0001cb3b0, 0xc0019195d0)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/baseapp/baseapp.go:258 +0x31
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).LoadLatestVersion(0xc000125520, 0xc000d78770, 0x7f9edc051d78)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/baseapp/baseapp.go:248 +0x42
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/gaia/v3/app.NewGaiaApp(0x205ef00, 0xc00115d9e0, 0x20761c0, 0xc000010150, 0x0, 0x0, 0xc000d60901, 0xc000517ef0, 0x7fffeb440f37, 0x13, ...)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/gaia/v3/app/app.go:409 +0x6b6a
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/gaia/v3/cmd/gaiad/cmd.newApp(0x205ef00, 0xc00115d9e0, 0x20761c0, 0xc000010150, 0x0, 0x0, 0x2020680, 0xc0010518c0, 0x20300000000000, 0x7f9ee0579fff)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/gaia/v3/cmd/gaiad/cmd/root.go:177 +0x9cf
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f75380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2066fc0, 0xc000f2a240, ...)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/server/start.go:236 +0x1dc
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f6f8c0, 0xc00101f720, 0x0, 0x1, 0x0, 0x0)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/server/start.go:120 +0x169
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/spf13/cobra.(*Command).execute(0xc000f6f8c0, 0xc00101f710, 0x1, 0x1, 0xc000f6f8c0, 0xc00101f710)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/spf13/cobra.(*Command).ExecuteC(0xc000ed8580, 0x0, 0x0, 0xc000ef9b20)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/spf13/cobra.(*Command).Execute(...)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/spf13/cobra@v1.1.1/command.go:895
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/spf13/cobra@v1.1.1/command.go:888
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000ed8580, 0xc000ef9b20, 0x12, 0x2079900, 0xc000f2a240)
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/cosmos-sdk@v0.40.0/server/cmd/execute.go:36 +0x265
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: main.main()
Jan 11 01:09:45 cosmos-testnet gaiad[1674]: #011github.com/cosmos/gaia/v3/cmd/gaiad/main.go:16 +0x45
```

## Version

v3.0.0

## Steps to Reproduce

Update from `v2.0.14` to `v3.0.0` on `gaia-13007` testnet.
If I roll back to `v2.0.14` everything works.
____

Also I do not see `gaiacli` anymore, only `gaiad` binary it seems is there. 
How do I use RPC interface in `v3.0.0` to query transactions to my account (`gaiacli rest-server`) ?

**Comment by zhangsj** [comment]
can not find gaiacli too

**Comment by tac0turtle** [comment]
Gaia v3 is not being used on mainnet nor on the testnet. There will be an upgrade process before it is used. Continue using v2.0.14 until that happens. 

> can not find gaiacli too

gaiacli was folded into gaiad. All the commands are there now.

**Comment by gituser** [comment]
@marbar3778 alright, thanks, will be waiting for an update.

**Comment by giovannirco** [comment]
Does this mean that I will not be able to scale gaiacli commands horizontally without spinning up a new node?

**Comment by shahankhatch** [comment]
@giovannirco Running the binary does not automatically spin up a node. The subcommands invoke various actions, one of which is to start the node itself, and other actions enable querying, etc.
