### ISSUE TITLE
Stargate Migration Guide

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#569]
The last upgrade contained a [detailed migration guide](https://github.com/cosmos/gaia/blob/master/docs/migration/cosmoshub-2.md).

While all of this content currently exists in scattered place (a lot of it probably in the [Stargate repo](https://github.com/cosmos/stargate), the rest maybe in the upgrade proposal itself), it would probably help to consolidate a single reference document for everyone like we did for the hub2->hub3 upgrade.

**Comment by ebuchman** [comment]
As part of the migration guide we should host/link to a recent snapshot of Cosmos Hub state so folks can test out the migration even if they don't have a synced node.

**Comment by ebuchman** [comment]
There is a Nov 1st hub full node state here:https://storage.googleapis.com/stargate-genesis/snapshot.tgz

And a nov 1 st hub export here https://storage.googleapis.com/stargate-genesis/3924406.cosmoshub-3.json

The export can be used with the instructions in https://github.com/cosmos/governance/pull/5/files#diff-318fcc82624ba9a70810f0aee8faaff95208ee45c40e6a9dc376255150feef1bR101 to test the migration

To be able to actually create blocks in testing, since this is a real Hub export, you'll need to replace the validator keys. An example validator replacement file looks like [this](https://github.com/cosmos/stargate-launch/blob/master/validator_replacement.json), but you need one that replaces at least +2/3 of validator power with keys you control (TODO how best to do this ?). 

Then you can run:

```
cosmos/gaia/build/gaiad migrate ~/3924406.cosmoshub-3.json --chain-id=cosmoshub-test-stargate-d --initial-height 3924407 --replacement-cons-keys ~/iqlusion_work/stargate/validator_replacement.json > new_genesis.json
```

then make a directory with `cosmos/gaia/build/gaiad init`

then move the genesis into it and `gaiad start`

then let all the crisis invariants assert

**Comment by zmanian** [comment]
This currently panics if `--replacement-cons-keys ~/iqlusion_work/stargate/validator_replacement.json` is passed in with

```
panic: genesisValidators[0] != req.Validators[0]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001034820, 0x0, 0xed5830c36, 0x0, 0xc0004f0600, 0x19, 0xc00104bf00, 0xc000dc4c00, 0x7d, 0x7d, ...)
  github.com/cosmos/cosmos-sdk@v0.41.0/baseapp/abci.go:80 +0x950
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0004dd0e0, 0x0, 0xed5830c36, 0x0, 0xc0004f0600, 0x19, 0xc00104bf00, 0xc000dc4c00, 0x7d, 0x7d, ...)
  github.com/tendermint/tendermint@v0.34.3/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0004e6930, 0x0, 0xed5830c36, 0x0, 0xc0004f0600, 0x19, 0xc00104bf00, 0xc000dc4c00, 0x7d, 0x7d, ...)
  github.com/tendermint/tendermint@v0.34.3/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc02df266b8, 0xb, 0x0, 0x0, 0x0, 0xc0004f0600, 0x19, 0x3be1b7, 0x0, 0x0, ...)
  github.com/tendermint/tendermint@v0.34.3/consensus/replay.go:319 +0x695
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc02df266b8, 0x5c4d7c0, 0xc000dea1a0, 0xc0011e2550, 0x1)
  github.com/tendermint/tendermint@v0.34.3/consensus/replay.go:268 +0x4d8
github.com/tendermint/tendermint/node.doHandshake(0x5c49740, 0xc00007f400, 0xb, 0x0, 0x0, 0x0, 0xc0004f0600, 0x19, 0x3be1b7, 0x0, ...)
  github.com/tendermint/tendermint@v0.34.3/node/node.go:277 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc000f32dc0, 0x5c2af00, 0xc000dc26e0, 0xc0001197c0, 0x5bf6420, 0xc00000e340, 0xc0001198c0, 0x5a35a70, 0xc000119c20, 0x5c34780, ...)
  github.com/tendermint/tendermint@v0.34.3/node/node.go:685 +0x1da5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f4dfa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5c3c8a0, 0xc000f1e620, ...)
  github.com/cosmos/cosmos-sdk@v0.41.0/server/start.go:244 +0x565
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f738c0, 0xc00104a120, 0x0, 0x2, 0x0, 0x0)
  github.com/cosmos/cosmos-sdk@v0.41.0/server/start.go:120 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000f738c0, 0xc00104a100, 0x2, 0x2, 0xc000f738c0, 0xc00104a100)
  github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ed6580, 0x0, 0x0, 0xc000f128c0)
  github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
  github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
  github.com/spf13/cobra@v1.1.1/command.go:888
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000ed6580, 0xc000f128c0, 0x17, 0x5c4f200, 0xc000f1e620)
  github.com/cosmos/cosmos-sdk@v0.41.0/server/cmd/execute.go:36 +0x265
main.main()
  github.com/cosmos/gaia/v4/cmd/gaiad/main.go:16 +0x45
```

**Comment by shahankhatch** [comment]
Zaki confirmed that the panic above can't be reproduced.
