### ISSUE TITLE
Rest Client Panic

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/gaia#7]
```
$ gaiacli rest-server --chain-id=chain-LldPl4 --home ./build/node0/gaiacli
panic: statik/fs: no zip data registered

goroutine 1 [running]:
main.registerSwaggerUI(0xc000a22dc0)
	/Users/aleksbez/go/src/github.com/cosmos/gaia/cmd/gaiacli/main.go:185 +0x14f
main.registerRoutes(0xc000a22dc0)
	/Users/aleksbez/go/src/github.com/cosmos/gaia/cmd/gaiacli/main.go:170 +0x43
github.com/cosmos/cosmos-sdk/client/lcd.ServeCommand.func1(0xc000aae000, 0xc0001c3f20, 0x0, 0x3, 0x0, 0x0)
	/Users/aleksbez/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.28.2-0.20190518230608-cfe31c409023/client/lcd/root.go:90 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000aae000, 0xc0001c3e60, 0x3, 0x3, 0xc000aae000, 0xc0001c3e60)
	/Users/aleksbez/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b4c80, 0x47bd75f, 0xc0001b4c80, 0x4b7a365)
	/Users/aleksbez/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/aleksbez/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001b4c80, 0x4cf3e48, 0x2, 0xc0004e3f00)
	/Users/aleksbez/go/pkg/mod/github.com/tendermint/tendermint@v0.31.5/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/aleksbez/go/src/github.com/cosmos/gaia/cmd/gaiacli/main.go:110 +0x8c8
```

**Comment by alexanderbez** [comment]
This is because we don't have the `statik.go` file that is used in the SDK's build. Not sure how to proceed here. Swagger will be served from Gaia so the build should happen in Gaia, right?
